using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FastCloner.SourceGenerator;

public class CloneCodeGenerator
{
    private readonly SemanticModel semanticModel;
    private readonly INamedTypeSymbol typeSymbol;
    private readonly TypeDeclarationSyntax typeDecl;
    private readonly Compilation compilation;
    private readonly HashSet<ITypeSymbol> processedTypes;
    private readonly StringBuilder source = new StringBuilder();
    private readonly ImmutableArray<UsingDirectiveSyntax> usings;

    public CloneCodeGenerator(Compilation compilation, TypeDeclarationSyntax typeDecl)
    {
        this.compilation = compilation;
        this.typeDecl = typeDecl;
        semanticModel = compilation.GetSemanticModel(typeDecl.SyntaxTree);
        typeSymbol = semanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol 
                      ?? throw new InvalidOperationException("Could not get type symbol");
        processedTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        
        usings = [
            ..typeDecl.SyntaxTree.GetRoot()
                .DescendantNodes()
                .OfType<UsingDirectiveSyntax>()
        ];
    }
    
    public string Generate()
    {
        WriteFileHeader();
        WriteUsings();
        WriteNamespace();
        WriteCloneClass();
        WriteHelperClasses();
        WriteFileFooter();

        return source.ToString();
    }

    private void WriteFileHeader()
    {
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
    }

    private void WriteUsings()
    {
        foreach (UsingDirectiveSyntax usingDir in usings.Distinct())
        {
            source.AppendLine(usingDir.ToString());
        }
        
        source.AppendLine();
    }

    private void WriteNamespace()
    {
        NamespaceDeclarationSyntax ns = typeDecl.Ancestors().OfType<NamespaceDeclarationSyntax>().FirstOrDefault();
        if (ns != null)
        {
            source.AppendLine($"namespace {ns.Name}");
            source.AppendLine("{");
        }
    }

    private void WriteCloneClass()
    {
        string typeName = typeDecl.Identifier.Text;
        
        source.AppendLine($"    public static class {typeName}Clone");
        source.AppendLine("    {");
        
        WritePublicCloneMethods();
        WritePrivateCloneMethods();
        
        source.AppendLine("    }");
    }

    private void WritePublicCloneMethods()
    {
        string typeName = typeSymbol.ToDisplayString();
        
        // w/o state
        source.AppendLine($"        public static {typeName} Clone({typeName} source)");
        source.AppendLine("        {");
        source.AppendLine("            return Clone(source, new FastCloneState());");
        source.AppendLine("        }");
        source.AppendLine();

        // with state
        source.AppendLine($"        public static {typeName} Clone({typeName} source, FastCloneState state)");
        source.AppendLine("        {");
        source.AppendLine("            if (source == null) return null;");
        source.AppendLine("            if (state.TryGetKnownRef(source, out var known)) return ({typeName})known;");
        source.AppendLine();
        source.AppendLine($"            var result = new {typeName}();");
        source.AppendLine("            state.AddKnownRef(source, result);");
        source.AppendLine();
        
        WritePropertyCloning();
        
        source.AppendLine("            return result;");
        source.AppendLine("        }");
    }

    private void WritePropertyCloning()
    {
        foreach (IPropertySymbol member in typeSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.DeclaredAccessibility != Accessibility.Public || member.IsReadOnly)
                continue;

            string propName = member.Name;
            ITypeSymbol propType = member.Type;
            
            if (IsSimpleType(propType))
            {
                source.AppendLine($"            result.{propName} = source.{propName};");
            }
            else
            {
                source.AppendLine($"            result.{propName} = Clone{GetCleanTypeName(propType)}(source.{propName}, state);");
                AnalyzeTypeForCloning(propType);
            }
        }
    }

    
    private static string GetCleanTypeName(ITypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(' ', '_');
    }
    
    private bool IsArrayType(string typeName)
    {
        return typeName.Contains("[]");
    }
    
    private void WritePrivateCloneMethods()
    {
        foreach (ITypeSymbol type in processedTypes)
        {
            if (IsCollectionType(type))
            {
                WriteCollectionCloneMethod(type);
            }
            else if (IsDictionaryType(type))
            {
                WriteDictionaryCloneMethod(type);
            }
            else if (type.TypeKind == TypeKind.Array)
            {
                WriteArrayCloneMethod(type);
            }
        }
    }
    
    private void WriteCollectionCloneMethod(ITypeSymbol type)
    {
        ITypeSymbol elementType = GetCollectionElementType(type);
        if (elementType == null) return;

        string typeName = type.ToDisplayString();
        source.AppendLine($"        private static {typeName} Clone{GetCleanTypeName(type)}({typeName} source, FastCloneState state)");
        source.AppendLine("        {");
        source.AppendLine("            if (source == null) return null;");
        source.AppendLine("            if (state.TryGetKnownRef(source, out var known)) return ({typeName})known;");
        source.AppendLine();
        source.AppendLine($"            var result = new {typeName}();");
        source.AppendLine("            state.AddKnownRef(source, result);");
        source.AppendLine();
        source.AppendLine("            foreach (var item in source)");
        source.AppendLine("            {");
        
        if (IsSimpleType(elementType))
        {
            source.AppendLine("                result.Add(item);");
        }
        else
        {
            source.AppendLine($"                result.Add(Clone{GetCleanTypeName(elementType)}(item, state));");
        }
        
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return result;");
        source.AppendLine("        }");
    }

    private void WriteDictionaryCloneMethod(ITypeSymbol type)
    {
        (ITypeSymbol KeyType, ITypeSymbol ValueType)? dictTypes = GetDictionaryTypes(type);
        if (dictTypes == null) return;

        (ITypeSymbol keyType, ITypeSymbol valueType) = dictTypes.Value;
        string typeName = type.ToDisplayString();
        
        source.AppendLine($"        private static {typeName} Clone{GetCleanTypeName(type)}({typeName} source, FastCloneState state)");
        source.AppendLine("        {");
        source.AppendLine("            if (source == null) return null;");
        source.AppendLine("            if (state.TryGetKnownRef(source, out var known)) return ({typeName})known;");
        source.AppendLine();
        source.AppendLine($"            var result = new {typeName}();");
        source.AppendLine("            state.AddKnownRef(source, result);");
        source.AppendLine();
        source.AppendLine("            foreach (var kvp in source)");
        source.AppendLine("            {");
        
        string keyClone = IsSimpleType(keyType) ? "kvp.Key" : $"Clone{GetCleanTypeName(keyType)}(kvp.Key, state)";
        string valueClone = IsSimpleType(valueType) ? "kvp.Value" : $"Clone{GetCleanTypeName(valueType)}(kvp.Value, state)";
        
        source.AppendLine($"                result.Add({keyClone}, {valueClone});");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return result;");
        source.AppendLine("        }");
    }
    
    private void WriteArrayCloneMethod(ITypeSymbol type)
    {
        // TODO: implement me
    }

    private void WriteHelperClasses()
    {
        source.AppendLine("    public class FastCloneState");
        source.AppendLine("    {");
        source.AppendLine("        private readonly Dictionary<object, object> _knownRefs = new();");
        source.AppendLine();
        source.AppendLine("        public void AddKnownRef(object original, object clone)");
        source.AppendLine("        {");
        source.AppendLine("            if (original != null)");
        source.AppendLine("                _knownRefs[original] = clone;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public bool TryGetKnownRef(object original, out object? clone)");
        source.AppendLine("        {");
        source.AppendLine("            return _knownRefs.TryGetValue(original, out clone);");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private void WriteFileFooter()
    {
        source.AppendLine("}");
    }

    private bool IsCollectionType(ITypeSymbol type)
    {
        return type.AllInterfaces.Any(i => 
            i.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_ICollection_T ||
            (i.MetadataName == "ICollection" && 
             i.ContainingNamespace.ToDisplayString() == "System.Collections"));
    }

    private bool IsDictionaryType(ITypeSymbol type)
    {
        return type.AllInterfaces.Any(i => 
            (i.MetadataName == "IDictionary`2" && 
             i.ContainingNamespace.ToDisplayString() == "System.Collections.Generic") ||
            (i.MetadataName == "IDictionary" && 
             i.ContainingNamespace.ToDisplayString() == "System.Collections"));
    }

    private ITypeSymbol GetCollectionElementType(ITypeSymbol type)
    {
        // generic ICollection<T>
        INamedTypeSymbol genericCollection = type.AllInterfaces.FirstOrDefault(i => 
            i.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_ICollection_T);
        
        if (genericCollection != null)
        {
            return genericCollection.TypeArguments[0];
        }

        // non-generic ICollection
        INamedTypeSymbol nonGenericCollection = type.AllInterfaces.FirstOrDefault(i => 
            i.MetadataName == "ICollection" && 
            i.ContainingNamespace.ToDisplayString() == "System.Collections");
        
        if (nonGenericCollection != null)
        {
            return compilation.GetSpecialType(SpecialType.System_Object);
        }

        return null;
    }

    private (ITypeSymbol KeyType, ITypeSymbol ValueType)? GetDictionaryTypes(ITypeSymbol type)
    {
        INamedTypeSymbol dictInterface = type.AllInterfaces.FirstOrDefault(i => 
            i.MetadataName == "IDictionary`2" && 
            i.ContainingNamespace.ToDisplayString() == "System.Collections.Generic");
        
        if (dictInterface != null)
        {
            return (dictInterface.TypeArguments[0], dictInterface.TypeArguments[1]);
        }

        // non-generic IDictionary
        INamedTypeSymbol nonGenericDict = type.AllInterfaces.FirstOrDefault(i => 
            i.MetadataName == "IDictionary" && 
            i.ContainingNamespace.ToDisplayString() == "System.Collections");
        
        if (nonGenericDict != null)
        {
            return (compilation.GetSpecialType(SpecialType.System_Object),
                compilation.GetSpecialType(SpecialType.System_Object));
        }

        return null;
    }

    private static bool IsSimpleType(ITypeSymbol type)
    {
        return type.IsValueType || 
               type.SpecialType == SpecialType.System_String ||
               type.TypeKind == TypeKind.Enum;
    }

    private void AnalyzeTypeForCloning(ITypeSymbol type)
    {
        if (!processedTypes.Add(type))
            return;
        
        foreach (ISymbol member in type.GetMembers())
        {
            if (member is IPropertySymbol property)
            {
                AnalyzeTypeForCloning(property.Type);
            }
            else if (member is IFieldSymbol field)
            {
                AnalyzeTypeForCloning(field.Type);
            }
        }
        
        if (IsCollectionType(type))
        {
            ITypeSymbol elementType = GetCollectionElementType(type);
            if (elementType != null)
                AnalyzeTypeForCloning(elementType);
        }
        else if (IsDictionaryType(type))
        {
            (ITypeSymbol KeyType, ITypeSymbol ValueType)? dictTypes = GetDictionaryTypes(type);
            if (dictTypes.HasValue)
            {
                AnalyzeTypeForCloning(dictTypes.Value.KeyType);
                AnalyzeTypeForCloning(dictTypes.Value.ValueType);
            }
        }
    }
}
