using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FastCloner.SourceGenerator;

internal sealed class CloneCodeGenerator
{
    private readonly CloneGeneratorContext _context;
    private readonly EquatableArray<GenericUsage> _usages;

    public CloneCodeGenerator(TypeModel model, EquatableArray<GenericUsage> usages)
    {
        _context = new CloneGeneratorContext(model);
        _usages = usages;
    }

    public string Generate()
    {
        PreAnalyzeHelperUsages();
        WriteFileHeader();
        WriteUsings();
        WriteNamespace();
        WriteExtensionClass();
        WriteFileFooter();

        return _context.Source.ToString();
    }

    private void PreAnalyzeHelperUsages()
    {
        AnalyzeMembers(_context.Model.Members);
        
        if (_context.Model.RelatedTypes != null)
        {
            foreach (TypeModel? related in _context.Model.RelatedTypes)
            {
                AnalyzeMembers(related.Members);
            }
        }
    }

    private void AnalyzeMembers(IEnumerable<MemberModel> members)
    {
        foreach (MemberModel member in members)
        {
            if (member.TypeKind == MemberTypeKind.Implicit)
            {
                _context.IncrementHelperUsage(member.TypeFullName);
            }
            else if (member.TypeKind == MemberTypeKind.Collection || 
                     member.TypeKind == MemberTypeKind.Array || 
                     member.TypeKind == MemberTypeKind.MultiDimArray)
            {
                if (member.ElementTypeName != null)
                {
                    if (_context.TryGetImplicitTypeModel(member.ElementTypeName, out _) ||
                        _context.TryGetMemberModel(member.ElementTypeName, out _))
                    {
                        _context.IncrementHelperUsage(member.ElementTypeName);
                    }
                }
            }
            else if (member.TypeKind == MemberTypeKind.Dictionary)
            {
                if (member.KeyTypeName != null)
                {
                    if (_context.TryGetImplicitTypeModel(member.KeyTypeName, out _) ||
                        _context.TryGetMemberModel(member.KeyTypeName, out _))
                    {
                        _context.IncrementHelperUsage(member.KeyTypeName);
                    }
                }
                
                if (member.ValueTypeName != null)
                {
                    if (_context.TryGetImplicitTypeModel(member.ValueTypeName, out _) ||
                        _context.TryGetMemberModel(member.ValueTypeName, out _))
                    {
                        _context.IncrementHelperUsage(member.ValueTypeName);
                    }
                }
            }
        }
    }

    private void WriteFileHeader()
    {
        StringBuilder sb = _context.Source;
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private void WriteUsings()
    {
        StringBuilder sb = _context.Source;
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using FastCloner.SourceGenerator.Shared;");
        
        if (_context.IsFastClonerAvailable)
        {
            sb.AppendLine("using FastCloner;");
        }

        sb.AppendLine();
    }

    private void WriteNamespace()
    {
        string ns = _context.Model.Namespace;
        if (!string.IsNullOrEmpty(ns))
        {
            _context.Source.AppendLine($"namespace {ns}");
            _context.Source.AppendLine("{");
        }
    }

    private void WriteExtensionClass()
    {
        string typeName = _context.Model.FullyQualifiedName;
        string fullTypeName = _context.Model.FullyQualifiedName;
        StringBuilder sb = _context.Source;
        
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Extension methods for cloning {_context.Model.Name}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static partial class {_context.Model.Name}FastDeepCloneExtensions");
        sb.AppendLine("    {");
        
        WritePublicFastDeepCloneMethod(typeName, fullTypeName);
        WritePrivateFastDeepCloneMethod(typeName, fullTypeName);
        WriteDerivedTypeHelpers();
        WriteClonerClass();
        
        CollectionHelperGenerator.GenerateHelpers(_context);

        sb.AppendLine("    }");
    }

    private void WritePublicFastDeepCloneMethod(string typeName, string fullTypeName)
    {
        StringBuilder sb = _context.Source;
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Performs deep clone of {_context.Model.Name}. This is a source generated method.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        /// <param name=\"source\">The object to clone.</param>");

        string typeParams = GetTypeParametersString();
        string constraints = GetTypeConstraintsString();
        bool isStruct = _context.Model.IsStruct;
        bool trustNullability = _context.Model.TrustNullability;
        string returnTypeSuffix = isStruct ? "" : "?";
        string paramTypeSuffix = (isStruct || trustNullability) ? "" : "?";
        string notNullAttr = CloneGeneratorContext.NotNullIfNotNullAttr(_context.Model.CodeAnalysisAvailable && !isStruct);
        if (!string.IsNullOrEmpty(notNullAttr))
            sb.AppendLine($"        {notNullAttr}");
        sb.AppendLine($"        public static {typeName}{returnTypeSuffix} FastDeepClone{typeParams}(this {typeName}{paramTypeSuffix} source){constraints}");
        sb.AppendLine("        {");
        
        bool hasInitOnlyWithCycles = _context.CanHaveCircularReferences && _context.Model.Members.Any(m => m.IsInitOnly);
        bool structWithReadonlyRefs = _context.Model.IsStruct && _context.Model.Members.Any(m => m is { IsValueType: false, IsReadOnly: true });

        if (!_context.Model.IsRefLikeType && _context.IsFastClonerAvailable && (hasInitOnlyWithCycles || structWithReadonlyRefs))
        {
             sb.AppendLine($"            return {CloneGeneratorContext.FastClonerDeepCloneCall("source")};");
             sb.AppendLine("        }");
             sb.AppendLine();
             return;
        }
        
        if (_context.Model.IsAbstract)
        {
            sb.AppendLine("            return InternalFastDeepClone(source, null);");
        }
        else if (!_context.NeedsStateTracking)
        {
            if (isStruct)
            {
                WriteStructCloneBodyDirect(typeName);
            }
            else
            {
                if (!trustNullability)
                {
                    sb.AppendLine("            if (source == null) return null;");
                }
                WriteCloneBody(typeName, fullTypeName, false);
            }
        }
        else
        {
            sb.AppendLine("            return InternalFastDeepClone(source, null);");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void WritePrivateFastDeepCloneMethod(string typeName, string fullTypeName)
    {
        StringBuilder sb = _context.Source;
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Performs deep clone of {_context.Model.Name} with circular reference tracking.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        /// <param name=\"source\">The object to clone.</param>");
        sb.AppendLine($"        /// <param name=\"state\">State for circular reference tracking. If null, a new state is created.</param>");

        string typeParams = GetTypeParametersString();
        string constraints = GetTypeConstraintsString();
        
        bool isStruct = _context.Model.IsStruct;
        bool trustNullability = _context.Model.TrustNullability;
        string returnTypeSuffix = isStruct ? "" : "?";
        string paramTypeSuffix = (isStruct || trustNullability) ? "" : "?";

        sb.AppendLine($"        internal static {typeName}{returnTypeSuffix} InternalFastDeepClone{typeParams}(this {typeName}{paramTypeSuffix} source, FcGeneratedCloneState? state){constraints}");
        sb.AppendLine("        {");
        
        bool hasInitOnlyWithCycles = _context.CanHaveCircularReferences && _context.Model.Members.Any(m => m.IsInitOnly);
        bool structWithReadonlyRefs = _context.Model.IsStruct && _context.Model.Members.Any(m => m is { IsValueType: false, IsReadOnly: true });
        
        if (!_context.Model.IsRefLikeType && _context.IsFastClonerAvailable && (hasInitOnlyWithCycles || structWithReadonlyRefs))
        {
             sb.AppendLine("            // Fallback to runtime cloning due to complex language features.");
             sb.AppendLine("            // Note: State is ignored here as the runtime handles its own circular reference tracking.");
             sb.AppendLine($"            return {CloneGeneratorContext.FastClonerDeepCloneCall("source")};");
             sb.AppendLine("        }");
             sb.AppendLine();
             return;
        }
        
        if (!isStruct && !trustNullability)
        {
            sb.AppendLine("            if (source == null) return null;");
        }
        
        if (_context.Model.IsAbstract)
        {
            WriteAbstractTypeDispatcher(typeName);
        }
        else if (_context.NeedsStateTracking)
        {
            _context.NeedsStateClass = true;
            sb.AppendLine("            var localState = state ?? new FcGeneratedCloneState();");

            if (!_context.Model.IsStruct)
            {
                sb.AppendLine("            var known = localState.GetKnownRef(source);");
                sb.AppendLine($"            if (known != null) return ({typeName})known;");
            }
            
            WriteCloneBody(typeName, fullTypeName, true, "localState");
        }
        else
        {
            _context.NeedsStateClass = true;
            sb.AppendLine("            if (state != null)");
            sb.AppendLine("            {");
            if (!_context.Model.IsStruct)
            {
                sb.AppendLine("                var known = state.GetKnownRef(source);");
                sb.AppendLine($"                if (known != null) return ({typeName})known;");
            }
            sb.AppendLine("            }");
            WriteCloneBody(typeName, fullTypeName, true, "state");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void WriteAbstractTypeDispatcher(string typeName)
    {
        StringBuilder sb = _context.Source;
        EquatableArray<TypeModel> derivedTypes = _context.Model.DerivedTypes;

        sb.AppendLine();
        sb.AppendLine("            // Dispatch to concrete type cloner based on runtime type");
        sb.AppendLine("            var runtimeType = source.GetType();");
        sb.AppendLine();

        foreach (TypeModel? derivedType in derivedTypes)
        {
            string derivedTypeName = derivedType.FullyQualifiedName;
            
            if (derivedType.Members.Count == 0)
            {
                string extensionClassName = $"{derivedType.Namespace}.{derivedType.Name}FastDeepCloneExtensions";
                if (string.IsNullOrEmpty(derivedType.Namespace))
                {
                    extensionClassName = $"{derivedType.Name}FastDeepCloneExtensions";
                }
                
                sb.AppendLine($"            if (runtimeType == typeof({derivedTypeName}))");
                sb.AppendLine($"                return ({typeName}){extensionClassName}.InternalFastDeepClone(({derivedTypeName})source, state);");
            }
            else
            {
                string helperName = $"Clone{GetSafeTypeName(derivedType.Name)}";
                _context.RegisterDerivedTypeHelper(derivedType, helperName);
                
                sb.AppendLine($"            if (runtimeType == typeof({derivedTypeName}))");
                sb.AppendLine($"                return ({typeName}){helperName}(({derivedTypeName})source, state);");
            }
            sb.AppendLine();
        }
        
        if (_context.IsFastClonerAvailable)
        {
            sb.AppendLine($"            return ({typeName}){CloneGeneratorContext.FastClonerDeepCloneCall("source")}!;");
        }
        else
        {
            sb.AppendLine($"            throw new InvalidOperationException($\"Cannot clone unknown derived type {{runtimeType.FullName}} of {_context.Model.Name}. \" +");
            sb.AppendLine("                \"Either add the derived type to this assembly, use [FastClonerInclude] to register it, \" +");
            sb.AppendLine("                \"or install the FastCloner NuGet package for runtime fallback.\");");
        }
    }

    private static string GetSafeTypeName(string typeName)
    {
        return typeName
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(' ', '_')
            .Replace('.', '_')
            .Replace('[', '_')
            .Replace(']', '_')
            .Replace('?', '_');
    }

    private void WriteDerivedTypeHelpers()
    {
        if (!_context.HasDerivedTypeHelpers)
            return;

        StringBuilder sb = _context.Source;

        foreach ((TypeModel derivedModel, string methodName) in _context.GetDerivedTypeHelpers())
        {
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Clones a {derivedModel.Name} instance (auto-generated for abstract base class).");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        private static {derivedModel.FullyQualifiedName} {methodName}({derivedModel.FullyQualifiedName} source, FcGeneratedCloneState? state)");
            sb.AppendLine("        {");
            
            if (derivedModel.NeedsStateTracking)
            {
                _context.NeedsStateClass = true;
                sb.AppendLine("            var localState = state ?? new FcGeneratedCloneState();");
                sb.AppendLine("            var known = localState.GetKnownRef(source);");
                sb.AppendLine($"            if (known != null) return ({derivedModel.FullyQualifiedName})known;");
                sb.AppendLine();
                
                WriteDerivedTypeCloneBody(derivedModel, true, "localState");
            }
            else
            {
                WriteDerivedTypeCloneBody(derivedModel, false, "state");
            }

            sb.AppendLine("        }");
        }
    }

    private void WriteDerivedTypeCloneBody(TypeModel derivedModel, bool useState, string stateVarName)
    {
        StringBuilder sb = _context.Source;
        string typeName = derivedModel.FullyQualifiedName;

        if (derivedModel.IsStruct)
        {
            sb.AppendLine($"            var result = source;");
            sb.AppendLine();

            foreach (MemberModel member in derivedModel.Members)
            {
                MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
            }

            sb.AppendLine("            return result;");
        }
        else
        {
            if (derivedModel.HasParameterlessConstructor)
            {
                if (useState)
                {
                    List<string> requiredMembers = [];
                    foreach (MemberModel member in derivedModel.Members)
                    {
                        if (member.IsRequired)
                        {
                            requiredMembers.Add($"                {member.Name} = default!");
                        }
                    }

                    if (requiredMembers.Count > 0)
                    {
                        sb.AppendLine($"            var result = new {typeName}");
                        sb.AppendLine("            {");
                        sb.AppendLine(string.Join(",\n", requiredMembers));
                        sb.AppendLine("            };");
                    }
                    else
                    {
                        sb.AppendLine($"            var result = new {typeName}();");
                    }

                    sb.AppendLine($"            {stateVarName}?.AddKnownRef(source, result);");
                    sb.AppendLine();

                    foreach (MemberModel member in derivedModel.Members)
                    {
                        MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
                    }

                    sb.AppendLine();
                    sb.AppendLine("            return result;");
                }
                else
                {
                    sb.AppendLine($"            var result = new {typeName}");
                    sb.AppendLine("            {");

                    List<string> memberAssignments = [];
                    foreach (MemberModel member in derivedModel.Members)
                    {
                        string assignment = MemberCloneGenerator.GetMemberAssignment(_context, member, "source", "null", "                ");
                        if (!string.IsNullOrEmpty(assignment))
                        {
                            memberAssignments.Add($"                {assignment}");
                        }
                    }

                    if (memberAssignments.Count > 0)
                    {
                        sb.AppendLine(string.Join(",\n", memberAssignments));
                    }

                    sb.AppendLine("            };");
                    sb.AppendLine();
                    sb.AppendLine("            return result;");
                }
            }
            else
            {
                ClassCloneBodyGenerator.WriteGetUninitializedObject(sb, typeName);
                
                if (useState)
                {
                    sb.AppendLine($"            {stateVarName}?.AddKnownRef(source, result);");
                }
                
                sb.AppendLine();

                foreach (MemberModel member in derivedModel.Members)
                {
                    MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
                }

                sb.AppendLine();
                sb.AppendLine("            return result;");
            }
        }
    }

    private string GetTypeParametersString()
    {
        return _context.Model.TypeParameters.Count == 0 ? string.Empty : $"<{string.Join(", ", _context.Model.TypeParameters)}>";
    }

    private string GetTypeConstraintsString()
    {
        if (_context.Model.TypeConstraints.Count == 0)
            return string.Empty;

        return " " + string.Join(" ", _context.Model.TypeConstraints);
    }

    private void WriteCloneBody(string typeName, string fullTypeName, bool useState, string? stateVarName = null)
    {
        if (_context.Model is { IsStruct: true, IsRecord: false })
        {
            WriteStructCloneBody(typeName, stateVarName ?? "state");
        }
        else
        {
            WriteClassCloneBody(typeName, fullTypeName, useState, stateVarName);
        }
    }

    private void WriteStructCloneBody(string typeName, string stateVarName = "state")
    {
        StringBuilder sb = _context.Source;
        sb.AppendLine($"            var result = source;");
        sb.AppendLine();

        foreach (MemberModel member in _context.Model.Members)
        {
            MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
        }

        sb.AppendLine("            return result;");
    }
    
    private void WriteStructCloneBodyDirect(string typeName)
    {
        StringBuilder sb = _context.Source;
        
        if (_context.Model.IsRecord)
        {
            List<string> deepCloneAssignments = [];
            foreach (MemberModel member in _context.Model.Members)
            {
                if (member.TypeKind == MemberTypeKind.Safe)
                    continue;
                if (member.IsReadOnly)
                    continue;
                
                string assignment = MemberCloneGenerator.GetMemberAssignment(_context, member, "source", "null", "                ");
                if (!string.IsNullOrEmpty(assignment))
                {
                    deepCloneAssignments.Add($"                {assignment}");
                }
            }
            
            if (deepCloneAssignments.Count == 0)
            {
                sb.AppendLine($"            return source with {{ }};");
            }
            else
            {
                sb.AppendLine($"            return source with");
                sb.AppendLine("            {");
                sb.AppendLine(string.Join(",\n", deepCloneAssignments));
                sb.AppendLine("            };");
            }
        }
        else
        {
            sb.AppendLine($"            var result = source;");
            sb.AppendLine();

            foreach (MemberModel member in _context.Model.Members)
            {
                MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", "null");
            }

            sb.AppendLine("            return result;");
        }
    }

    private void WriteClassCloneBody(string typeName, string fullTypeName, bool useState, string? stateVarName = null)
    {
        ClassCloneBodyGenerator.WriteClassCloneBody(_context, typeName, useState, stateVarName, useNullConditional: true, sourceVarName: "source");
    }
    
    private void WriteClonerClass()
    {
        if (!_context.NeedsClonerClass)
            return;

        StringBuilder sb = _context.Source;
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Helper class for cloning generic types.");
        sb.AppendLine("        /// </summary>");

        string typeParams = GetTypeParametersString();
        string constraints = GetTypeConstraintsString();
        
        string[]? typeParamsArray = _context.Model.TypeParameters.GetArray();
        if (typeParamsArray == null || typeParamsArray.Length == 0)
        {
            sb.AppendLine($"        private static class Cloner<T>");
            sb.AppendLine("        {");
            sb.AppendLine("            public static T Clone(T source, FcGeneratedCloneState? state)");
        }
        else
        {
            sb.AppendLine($"        private static class Cloner{typeParams}{constraints}");
            sb.AppendLine("        {");

            string firstTypeParam = typeParamsArray[0];
            sb.AppendLine($"            public static {firstTypeParam} Clone({firstTypeParam} source, FcGeneratedCloneState? state)");
        }
        
        sb.AppendLine("            {");
        sb.AppendLine("                if (source == null) return default!;");
        
        foreach (GenericUsage usage in _usages)
        {
            if (usage.GenericTypeMetadataName != _context.Model.FullyQualifiedName)
                continue;
            
            foreach (MemberModel nested in usage.NestedHelpers)
            {
                _context.GetOrCreateHelperMethodName(nested);
            }
            foreach (TypeModel? implicitType in usage.ImplicitTypes)
            {
                _context.RegisterImplicitType(implicitType);
                _context.GetOrCreateHelperMethodName(implicitType.FullyQualifiedName);
            }
                
            string argType = usage.ArgumentTypeMetadataName;
            string castTypeParam = typeParamsArray == null || typeParamsArray.Length == 0
                ? "T" 
                : typeParamsArray[0];
            
            if (usage.IsSafe)
            {
                sb.AppendLine($"                if (typeof({castTypeParam}) == typeof({argType})) return ({castTypeParam})(object)source;");
            }
            else if (usage.IsClonable && !string.IsNullOrEmpty(usage.ExtensionClassFQN))
            {
                sb.AppendLine($"                if (typeof({castTypeParam}) == typeof({argType}))");
                sb.AppendLine($"                    return ({castTypeParam})(object)({usage.ExtensionClassFQN}.FastDeepClone(({argType})(object)source)!);");
            }
            else if (usage.CollectionModel != null)
            {
                MemberModel collectionModel = usage.CollectionModel.Value;
                string helperName = _context.GetOrCreateHelperMethodName(collectionModel);
                bool needsState = MemberCloneGenerator.MemberNeedsCircularRefTracking(_context, collectionModel);
                
                string callArgs = needsState 
                    ? $"(({argType})(object)source, state)" 
                    : $"(({argType})(object)source)";

                sb.AppendLine($"                if (typeof({castTypeParam}) == typeof({argType}))");
                sb.AppendLine($"                    return ({castTypeParam})(object){helperName}{typeParams}{callArgs}!;");
            }
            else
            {
                if (_context.TryGetImplicitTypeModel(argType, out TypeModel implicitModel))
                {
                     string helperName = _context.GetOrCreateHelperMethodName(argType);
                     bool needsState = implicitModel.NeedsStateTracking && _context.NeedsStateTracking;
                     string callArgs = needsState 
                        ? $"(({argType})(object)source, state)" 
                        : $"(({argType})(object)source)";

                     sb.AppendLine($"                if (typeof({castTypeParam}) == typeof({argType}))");
                     sb.AppendLine($"                    return ({castTypeParam})(object){helperName}{typeParams}{callArgs}!;");
                }
            }
        }
        
        string fallbackCastTypeParam = (typeParamsArray == null || typeParamsArray.Length == 0)
            ? "T" 
            : typeParamsArray[0];
        
        if (_context.IsFastClonerAvailable)
        {
            sb.AppendLine($"                return ({fallbackCastTypeParam}){CloneGeneratorContext.FastClonerDeepCloneCall("source")}!;");
        }
        else
        {
            sb.AppendLine("                return source;");
        }
        sb.AppendLine("            }");

        sb.AppendLine("        }");
    }

    private void WriteFileFooter()
    {
        if (!string.IsNullOrEmpty(_context.Model.Namespace))
        {
            _context.Source.AppendLine("}");
        }
    }
}
