using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace FastCloner.SourceGenerator;

/// <summary>
/// Generates FastDeepClone() extension methods for types marked with [FastClonerClonable].
/// </summary>
internal sealed class CloneCodeGenerator
{
    private readonly CloneGeneratorContext _context;
    private readonly EquatableArray<GenericUsage> _usages;

    public CloneCodeGenerator(TypeModel model, EquatableArray<GenericUsage> usages)
    {
        _context = new CloneGeneratorContext(model);
        _usages = usages;
    }

    public string Generate()
    {
        WriteFileHeader();
        WriteUsings();
        WriteNamespace();
        WriteExtensionClass();
        WriteFileFooter();

        return _context.Source.ToString();
    }

    private void WriteFileHeader()
    {
        var sb = _context.Source;
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private void WriteUsings()
    {
        var sb = _context.Source;
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using FastCloner.SourceGenerator.Shared;");

        // Add FormatterServices if type doesn't have parameterless constructor
        // Also check derived types for abstract classes
        var needsFormatterServices = ClassCloneBodyGenerator.NeedsFormatterServices(_context.Model) ||
                                     ClassCloneBodyGenerator.NeedsFormatterServices(_context.Model.DerivedTypes);
        if (needsFormatterServices)
        {
            sb.AppendLine("using System.Runtime.Serialization;");
        }

        // Only add FastCloner using if the library is available
        if (_context.IsFastClonerAvailable)
        {
            sb.AppendLine("using FastCloner;");
        }

        sb.AppendLine();
    }

    private void WriteNamespace()
    {
        var ns = _context.Model.Namespace;
        if (!string.IsNullOrEmpty(ns))
        {
            _context.Source.AppendLine($"namespace {ns}");
            _context.Source.AppendLine("{");
        }
    }

    private void WriteExtensionClass()
    {
        // Use the fully qualified name from TypeModel
        var typeName = _context.Model.FullyQualifiedName;
        var fullTypeName = _context.Model.FullyQualifiedName;
        var sb = _context.Source;

        // FcGeneratedCloneState is now in FastCloner.SourceGenerator.Shared - no need to generate it

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Extension methods for cloning {_context.Model.Name}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static partial class {_context.Model.Name}FastDeepCloneExtensions");
        sb.AppendLine("    {");

        // Generate public FastDeepClone() without state parameter
        WritePublicFastDeepCloneMethod(typeName, fullTypeName);

        // Always generate InternalFastDeepClone for Clonable types, even if they don't detect circular references
        WritePrivateFastDeepCloneMethod(typeName, fullTypeName);

        // Generate helper methods for derived types (for abstract classes)
        WriteDerivedTypeHelpers();

        // Generate Cloner<T> helper class (private nested class)
        // Must be generated before helpers to register its dependencies
        WriteClonerClass();

        // Generate helper methods for nested types
        CollectionHelperGenerator.GenerateHelpers(_context);

        sb.AppendLine("    }");
    }

    private void WritePublicFastDeepCloneMethod(string typeName, string fullTypeName)
    {
        var sb = _context.Source;
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Performs deep clone of {_context.Model.Name}. This is a source generated method.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        /// <param name=\"source\">The object to clone.</param>");

        var typeParams = GetTypeParametersString();
        var constraints = GetTypeConstraintsString();

        // For structs (value types), use non-nullable signatures since structs can't be null
        var isStruct = _context.Model.IsStruct;
        var nullableSuffix = isStruct ? "" : "?";

        sb.AppendLine($"        public static {typeName}{nullableSuffix} FastDeepClone{typeParams}(this {typeName}{nullableSuffix} source){constraints}");
        sb.AppendLine("        {");

        // For abstract classes, always use the internal method with state (for potential circular refs)
        if (_context.Model.IsAbstract)
        {
            sb.AppendLine("            return InternalFastDeepClone(source, null);");
        }
        // Optimization: When no circular references are possible, inline the clone logic directly
        // instead of calling through InternalFastDeepClone (saves a method call)
        else if (!_context.CanHaveCircularReferences)
        {
            // For structs (value types), no null check needed - just clone directly
            if (isStruct)
            {
                // For structs, source is already non-nullable, use it directly
                WriteStructCloneBodyDirect(typeName);
            }
            else
            {
                sb.AppendLine("            if (source == null) return null;");
                WriteCloneBody(typeName, fullTypeName, false);
            }
        }
        else
        {
            sb.AppendLine("            return InternalFastDeepClone(source, null);");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void WritePrivateFastDeepCloneMethod(string typeName, string fullTypeName)
    {
        var sb = _context.Source;
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Performs deep clone of {_context.Model.Name} with circular reference tracking.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        /// <param name=\"source\">The object to clone.</param>");
        sb.AppendLine($"        /// <param name=\"state\">State for circular reference tracking. If null, a new state is created.</param>");

        var typeParams = GetTypeParametersString();
        var constraints = GetTypeConstraintsString();

        // For structs (value types), use non-nullable signatures since structs can't be null
        var isStruct = _context.Model.IsStruct;
        var nullableSuffix = isStruct ? "" : "?";

        sb.AppendLine($"        internal static {typeName}{nullableSuffix} InternalFastDeepClone{typeParams}(this {typeName}{nullableSuffix} source, object? state){constraints}");
        sb.AppendLine("        {");
        
        // For structs (value types), no null check needed
        if (!isStruct)
        {
            sb.AppendLine("            if (source == null) return null;");
        }

        // For abstract classes, generate a type dispatcher
        if (_context.Model.IsAbstract)
        {
            WriteAbstractTypeDispatcher(typeName);
        }
        // Only use state if circular references are possible
        else if (_context.CanHaveCircularReferences)
        {
            _context.NeedsStateClass = true;
            // Cast state to local type or create new one - allows sharing state across different extension classes
            sb.AppendLine("            var localState = (state as FcGeneratedCloneState) ?? new FcGeneratedCloneState();");

            if (!_context.Model.IsStruct)
            {
                sb.AppendLine("            var known = localState.GetKnownRef(source);");
                sb.AppendLine($"            if (known != null) return ({typeName})known;");
            }

            // Use localState in WriteCloneBody - need to pass it as a variable name
            WriteCloneBody(typeName, fullTypeName, true, "localState");
        }
        else
        {
            // If circular references aren't possible, state can remain null and won't be used
            WriteCloneBody(typeName, fullTypeName, false);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void WriteAbstractTypeDispatcher(string typeName)
    {
        var sb = _context.Source;
        var derivedTypes = _context.Model.DerivedTypes;

        sb.AppendLine();
        sb.AppendLine("            // Dispatch to concrete type cloner based on runtime type");
        sb.AppendLine("            var runtimeType = source.GetType();");
        sb.AppendLine();

        foreach (var derivedType in derivedTypes)
        {
            var derivedTypeName = derivedType.FullyQualifiedName;
            
            // Check if the derived type has its own [FastClonerClonable] attribute
            // If so, use its generated extension method; otherwise use our helper
            if (derivedType.Members.Count == 0)
            {
                // Minimal model - has its own [FastClonerClonable], use its extension
                var extensionClassName = $"{derivedType.Namespace}.{derivedType.Name}FastDeepCloneExtensions";
                if (string.IsNullOrEmpty(derivedType.Namespace))
                {
                    extensionClassName = $"{derivedType.Name}FastDeepCloneExtensions";
                }
                
                sb.AppendLine($"            if (runtimeType == typeof({derivedTypeName}))");
                sb.AppendLine($"                return ({typeName}){extensionClassName}.InternalFastDeepClone(({derivedTypeName})source, state);");
            }
            else
            {
                // Full model - auto-generated, use our helper method
                var helperName = $"Clone{GetSafeTypeName(derivedType.Name)}";
                _context.RegisterDerivedTypeHelper(derivedType, helperName);
                
                sb.AppendLine($"            if (runtimeType == typeof({derivedTypeName}))");
                sb.AppendLine($"                return ({typeName}){helperName}(({derivedTypeName})source, state);");
            }
            sb.AppendLine();
        }

        // Fallback for unknown derived types
        if (_context.IsFastClonerAvailable)
        {
            sb.AppendLine("            // Fallback for unknown derived types - use runtime cloner");
            sb.AppendLine($"            return ({typeName})FastCloner.DeepClone(source);");
        }
        else
        {
            sb.AppendLine("            // No runtime cloner available - throw for unknown derived types");
            sb.AppendLine($"            throw new InvalidOperationException($\"Cannot clone unknown derived type {{runtimeType.FullName}} of {_context.Model.Name}. \" +");
            sb.AppendLine("                \"Either add the derived type to this assembly, use [FastClonerInclude] to register it, \" +");
            sb.AppendLine("                \"or install the FastCloner NuGet package for runtime fallback.\");");
        }
    }

    private static string GetSafeTypeName(string typeName)
    {
        return typeName
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_')
            .Replace(' ', '_')
            .Replace('.', '_')
            .Replace('[', '_')
            .Replace(']', '_')
            .Replace('?', '_');
    }

    private void WriteDerivedTypeHelpers()
    {
        if (!_context.HasDerivedTypeHelpers)
            return;

        var sb = _context.Source;

        foreach (var (derivedModel, methodName) in _context.GetDerivedTypeHelpers())
        {
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Clones a {derivedModel.Name} instance (auto-generated for abstract base class).");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        private static {derivedModel.FullyQualifiedName} {methodName}({derivedModel.FullyQualifiedName} source, object? state)");
            sb.AppendLine("        {");

            // Create a temporary context for this derived type
            var derivedContext = new DerivedTypeCloneContext(_context, derivedModel);
            
            if (derivedModel.CanHaveCircularReferences)
            {
                _context.NeedsStateClass = true;
                sb.AppendLine("            var localState = (state as FcGeneratedCloneState) ?? new FcGeneratedCloneState();");
                sb.AppendLine("            var known = localState.GetKnownRef(source);");
                sb.AppendLine($"            if (known != null) return ({derivedModel.FullyQualifiedName})known;");
                sb.AppendLine();
                
                WriteDerivedTypeCloneBody(derivedModel, true, "localState");
            }
            else
            {
                WriteDerivedTypeCloneBody(derivedModel, false, "state");
            }

            sb.AppendLine("        }");
        }
    }

    private void WriteDerivedTypeCloneBody(TypeModel derivedModel, bool useState, string stateVarName)
    {
        var sb = _context.Source;
        var typeName = derivedModel.FullyQualifiedName;

        if (derivedModel.IsStruct)
        {
            sb.AppendLine($"            var result = source;");
            sb.AppendLine();

            foreach (var member in derivedModel.Members)
            {
                MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
            }

            sb.AppendLine("            return result;");
        }
        else
        {
            if (derivedModel.HasParameterlessConstructor)
            {
                if (useState)
                {
                    sb.AppendLine($"            var result = new {typeName}();");
                    sb.AppendLine($"            {stateVarName}?.AddKnownRef(source, result);");
                    sb.AppendLine();

                    foreach (var member in derivedModel.Members)
                    {
                        MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
                    }

                    sb.AppendLine();
                    sb.AppendLine("            return result;");
                }
                else
                {
                    sb.AppendLine($"            var result = new {typeName}");
                    sb.AppendLine("            {");

                    var memberAssignments = new List<string>();
                    foreach (var member in derivedModel.Members)
                    {
                        var assignment = MemberCloneGenerator.GetMemberAssignment(_context, member, "source", "null");
                        if (!string.IsNullOrEmpty(assignment))
                        {
                            memberAssignments.Add($"                {assignment}");
                        }
                    }

                    if (memberAssignments.Count > 0)
                    {
                        sb.AppendLine(string.Join(",\n", memberAssignments));
                    }

                    sb.AppendLine("            };");
                    sb.AppendLine();
                    sb.AppendLine("            return result;");
                }
            }
            else
            {
                sb.AppendLine($"            var result = ({typeName})FormatterServices.GetUninitializedObject(typeof({typeName}));");
                
                if (useState)
                {
                    sb.AppendLine($"            {stateVarName}?.AddKnownRef(source, result);");
                }
                
                sb.AppendLine();

                foreach (var member in derivedModel.Members)
                {
                    MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
                }

                sb.AppendLine();
                sb.AppendLine("            return result;");
            }
        }
    }

    /// <summary>
    /// Helper class for generating clone code for derived types within the abstract class context.
    /// </summary>
    private class DerivedTypeCloneContext
    {
        private readonly CloneGeneratorContext _parentContext;
        private readonly TypeModel _derivedModel;

        public DerivedTypeCloneContext(CloneGeneratorContext parentContext, TypeModel derivedModel)
        {
            _parentContext = parentContext;
            _derivedModel = derivedModel;
        }

        public TypeModel Model => _derivedModel;
        public StringBuilder Source => _parentContext.Source;
        public bool IsFastClonerAvailable => _parentContext.IsFastClonerAvailable;
    }

    private string GetTypeParametersString()
    {
        if (_context.Model.TypeParameters.Count == 0)
            return string.Empty;

        return $"<{string.Join(", ", _context.Model.TypeParameters)}>";
    }

    private string GetTypeConstraintsString()
    {
        if (_context.Model.TypeConstraints.Count == 0)
            return string.Empty;

        return " " + string.Join(" ", _context.Model.TypeConstraints);
    }

    private void WriteCloneBody(string typeName, string fullTypeName, bool useState, string? stateVarName = null)
    {
        // Record structs should use 'with' expression like record classes
        if (_context.Model.IsStruct && !_context.Model.IsRecord)
        {
            WriteStructCloneBody(typeName, stateVarName ?? "state");
        }
        else
        {
            // Classes and record structs both use this path
            WriteClassCloneBody(typeName, fullTypeName, useState, stateVarName);
        }
    }

    private void WriteStructCloneBody(string typeName, string stateVarName = "state")
    {
        var sb = _context.Source;
        // For structs, 'source' is non-nullable (no extraction needed)
        sb.AppendLine($"            var result = source;");
        sb.AppendLine();

        foreach (var member in _context.Model.Members)
        {
            MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", stateVarName);
        }

        sb.AppendLine("            return result;");
    }

    /// <summary>
    /// Writes struct clone body using 'source' directly (for non-nullable struct signatures).
    /// </summary>
    private void WriteStructCloneBodyDirect(string typeName)
    {
        var sb = _context.Source;
        
        // For record structs, use 'with' expression
        if (_context.Model.IsRecord)
        {
            // Collect members that need deep cloning
            var deepCloneAssignments = new System.Collections.Generic.List<string>();
            foreach (var member in _context.Model.Members)
            {
                if (member.TypeKind == MemberTypeKind.Safe)
                    continue;
                if (member.IsReadOnly)
                    continue;
                
                var assignment = MemberCloneGenerator.GetMemberAssignment(_context, member, "source", "null");
                if (!string.IsNullOrEmpty(assignment))
                {
                    deepCloneAssignments.Add($"                {assignment}");
                }
            }
            
            if (deepCloneAssignments.Count == 0)
            {
                sb.AppendLine($"            return source with {{ }};");
            }
            else
            {
                sb.AppendLine($"            return source with");
                sb.AppendLine("            {");
                sb.AppendLine(string.Join(",\n", deepCloneAssignments));
                sb.AppendLine("            };");
            }
        }
        else
        {
            // Regular structs: copy and modify
            sb.AppendLine($"            var result = source;");
            sb.AppendLine();

            foreach (var member in _context.Model.Members)
            {
                MemberCloneGenerator.WriteMemberCloning(_context, member, "result", "source", "null");
            }

            sb.AppendLine("            return result;");
        }
    }

    private void WriteClassCloneBody(string typeName, string fullTypeName, bool useState, string? stateVarName = null)
    {
        // Use null-conditional operator for CloneCodeGenerator since state might be null
        // For structs, source is non-nullable (no extraction needed)
        ClassCloneBodyGenerator.WriteClassCloneBody(_context, typeName, useState, stateVarName, useNullConditional: true, sourceVarName: "source");
    }


    private void WriteClonerClass()
    {
        if (!_context.NeedsClonerClass)
            return;

        var sb = _context.Source;
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Helper class for cloning generic types.");
        sb.AppendLine("        /// </summary>");
        
        var typeParams = GetTypeParametersString();
        var constraints = GetTypeConstraintsString();
        
        sb.AppendLine($"        private static class Cloner{typeParams}{constraints}");
        sb.AppendLine("        {");

        sb.AppendLine("            public static T Clone(T source, object? state)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (source == null) return default;");
        
        // Generate dispatch for known usages (Available even without FastCloner runtime)
        foreach (var usage in _usages)
        {
            // Filter usages relevant to THIS generic type definition
            if (usage.GenericTypeMetadataName != _context.Model.FullyQualifiedName)
                continue;

            // Register dependencies
            foreach (var nested in usage.NestedHelpers)
            {
                _context.GetOrCreateHelperMethodName(nested);
            }
            foreach (var implicitType in usage.ImplicitTypes)
            {
                _context.RegisterImplicitType(implicitType);
                _context.GetOrCreateHelperMethodName(implicitType.FullyQualifiedName);
            }
                
            var argType = usage.ArgumentTypeMetadataName;
            
            if (usage.IsSafe)
            {
                sb.AppendLine($"                if (typeof(T) == typeof({argType})) return (T)(object)source;");
            }
            else if (usage.IsClonable && !string.IsNullOrEmpty(usage.ExtensionClassFQN))
            {
                // Generate dispatch to concrete FastDeepClone
                sb.AppendLine($"                if (typeof(T) == typeof({argType}))");
                sb.AppendLine($"                    return (T)(object)({usage.ExtensionClassFQN}.FastDeepClone(({argType})(object)source)!);");
            }
            else if (usage.CollectionModel != null)
            {
                // Get helper name for the collection type
                MemberModel collectionModel = usage.CollectionModel.Value;
                var helperName = _context.GetOrCreateHelperMethodName(collectionModel);
                
                // Determine if helper needs state
                var needsState = MemberCloneGenerator.MemberNeedsCircularRefTracking(_context, collectionModel);
                
                var callArgs = needsState 
                    ? $"(({argType})(object)source, state as FcGeneratedCloneState)" 
                    : $"(({argType})(object)source)";

                sb.AppendLine($"                if (typeof(T) == typeof({argType}))");
                sb.AppendLine($"                    return (T)(object){helperName}{typeParams}{callArgs};");
            }
            else
            {
                // Check if it is an implicit type itself
                if (_context.TryGetImplicitTypeModel(argType, out var implicitModel))
                {
                     // Generate dispatch to implicit helper
                     var helperName = _context.GetOrCreateHelperMethodName(argType);
                     var needsState = implicitModel.CanHaveCircularReferences && _context.CanHaveCircularReferences;
                     var callArgs = needsState 
                        ? $"(({argType})(object)source, state as FcGeneratedCloneState)" 
                        : $"(({argType})(object)source)";

                     sb.AppendLine($"                if (typeof(T) == typeof({argType}))");
                     sb.AppendLine($"                    return (T)(object){helperName}{typeParams}{callArgs};");
                }
            }
        }
        
        if (_context.IsFastClonerAvailable)
        {
            sb.AppendLine("                // If FastCloner is available, delegate to it for deep cloning");
            sb.AppendLine("                return (T)FastCloner.DeepClone(source);");
        }
        else
        {
            sb.AppendLine("                // Fallback: If FastCloner is not available, we can only safely clone");
            sb.AppendLine("                // types that are effectively safe (value types, strings, etc.) by returning them.");
            sb.AppendLine("                // For other types, this results in a shallow copy/identity return,");
            sb.AppendLine("                // which is the best we can do without the runtime library.");
            sb.AppendLine("                return source;");
        }
        sb.AppendLine("            }");

        sb.AppendLine("        }");
    }

    private void WriteFileFooter()
    {
        if (!string.IsNullOrEmpty(_context.Model.Namespace))
        {
            _context.Source.AppendLine("}");
        }
    }
}
