using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FastCloner.Internalization.Builder;

internal static class Program
{
    private const string DefaultAttributionHeader = """
/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/
""";

    private static int Main(string[] args)
    {
        try
        {
            BuildOptions? options = BuildOptions.Parse(args);
            if (options is null)
            {
                PrintUsage();
                return 1;
            }

            BuildReport report = BuildInternalizedSources(options);
            report.Print();

            return report.HasErrors ? 1 : 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("Build failed.");
            Console.Error.WriteLine(ex);
            return 2;
        }
    }

    private static BuildReport BuildInternalizedSources(BuildOptions options)
    {
        if (!Directory.Exists(options.InputRoot))
            throw new DirectoryNotFoundException($"Input root not found: {options.InputRoot}");

        string[] files = RuntimeManifest.DiscoverRuntimeFiles(options.InputRoot, options.RuntimeOnly);
        BuildReport report = new(options, files.Length);
        HashSet<string> symbols = options.GetPreprocessorSymbols();
        CSharpParseOptions parseOptions = new(languageVersion: LanguageVersion.Preview, preprocessorSymbols: symbols);

        // Pass 1: transform all files, collect the union of all usings across every source file.
        Dictionary<string, CompilationUnitSyntax> transformed = new(StringComparer.Ordinal);
        HashSet<string> allUsings = new(StringComparer.Ordinal);

        foreach (string file in files)
        {
            string relativePath = Path.GetRelativePath(options.InputRoot, file).Replace('\\', '/');
            string source = File.ReadAllText(file);

            PruneResult prune = PreprocessorPruner.Transform(source, options.Preprocessor);
            source = prune.Text;
            report.PrunedDirectiveLines += prune.PrunedDirectiveLines;
            report.PrunedBranchLines += prune.PrunedBranchLines;

            SyntaxTree tree = CSharpSyntaxTree.ParseText(source, parseOptions);
            CompilationUnitSyntax root = tree.GetCompilationUnitRoot();

            foreach (UsingDirectiveSyntax u in root.Usings)
            {
                if (u.Alias is not null || u.StaticKeyword != default)
                    continue;
                string? name = u.Name?.ToString();
                if (!String.IsNullOrWhiteSpace(name))
                    allUsings.Add(name.StartsWith("global::", StringComparison.Ordinal) ? name["global::".Length..] : name);
            }

            var rewriter = new InternalizationRewriter(options, report);
            CompilationUnitSyntax rewrittenRoot = (CompilationUnitSyntax)rewriter.Visit(root)!;
            transformed[relativePath] = rewrittenRoot;
        }

        // Source project uses <ImplicitUsings>enable</ImplicitUsings>, so its files don't declare
        // the SDK-default usings explicitly. Discover them from the source csproj.
        foreach (string ns in DiscoverSourceImplicitUsings(options.InputRoot))
            allUsings.Add(ns);

        // Remove the source project's own namespaces — they've been rewritten to the target namespace
        // and would cause unresolvable CS0234 errors that cascade through the semantic model.
        allUsings.RemoveWhere(static ns => ns.Equals(InternalizationRewriter.SourceRootNamespace, StringComparison.Ordinal) ||
                                           ns.StartsWith(InternalizationRewriter.SourceRootNamespace + ".", StringComparison.Ordinal));

        // Inject the full union of usings into every file so the compilation resolves all symbols.
        foreach (string path in transformed.Keys.ToList())
            transformed[path] = AddAllCandidateUsings(transformed[path], allUsings, options.ImplicitUsings);

        // Pass 2: optionally qualify selected external metadata type references so generated code
        // cannot collide with consumer-defined namespaces/types.
        if (options.FullyQualifiedMetadataPrefixes.Count > 0)
            transformed = QualifyMetadataTypeReferences(transformed, parseOptions, options.ImplicitUsings, options.FullyQualifiedMetadataPrefixes);

        // Pass 3: compile all files together, ask the compiler which usings are unnecessary (CS8019).
        Dictionary<string, HashSet<int>> unnecessaryUsingSpans = FindUnnecessaryUsings(transformed, parseOptions, options.ImplicitUsings);

        // Pass 4: strip compiler-flagged usings + implicit usings, normalize, apply global:: rewrites, add header.
        Dictionary<string, string> generated = new(StringComparer.Ordinal);
        foreach ((string relativePath, CompilationUnitSyntax unit) in transformed)
        {
            HashSet<int> unnecessarySpanStarts = unnecessaryUsingSpans.GetValueOrDefault(relativePath) ?? [];
            CompilationUnitSyntax trimmed = StripUnnecessaryUsings(unit, unnecessarySpanStarts, options.ImplicitUsings);
            string rewritten = trimmed.NormalizeWhitespace(eol: "\n").ToFullString() + "\n";
            rewritten = rewritten.Replace("global::FastCloner.", $"global::{options.RootNamespace}.", StringComparison.Ordinal);
            rewritten = rewritten.Replace("global::FastCloner", $"global::{options.RootNamespace}", StringComparison.Ordinal);
            rewritten = AddGeneratedHeader(rewritten, options);
            generated[relativePath] = rewritten;
        }

        if (options.DryRun)
        {
            foreach (string path in generated.Keys.OrderBy(x => x, StringComparer.Ordinal))
                Console.WriteLine($"[dry-run] {path}");
            if (!options.NoLicense)
            {
                string? sourceLicense = GetSourceLicensePath(options.InputRoot);
                if (!String.IsNullOrWhiteSpace(sourceLicense))
                    Console.WriteLine($"[dry-run] LICENSE <= {sourceLicense}");
            }
        }
        else
        {
            Directory.CreateDirectory(options.Output);

            foreach ((string relativePath, string contents) in generated.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                string outPath = Path.Combine(options.Output, relativePath.Replace('/', Path.DirectorySeparatorChar));
                string? outDir = Path.GetDirectoryName(outPath);
                if (!String.IsNullOrEmpty(outDir))
                    Directory.CreateDirectory(outDir);

                File.WriteAllText(outPath, contents, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                report.WrittenFiles++;
            }

            if (!options.NoLicense)
            {
                string? sourceLicense = GetSourceLicensePath(options.InputRoot);
                if (!String.IsNullOrWhiteSpace(sourceLicense))
                {
                    string targetLicense = Path.Combine(options.Output, "LICENSE");
                    File.Copy(sourceLicense, targetLicense, overwrite: true);
                    report.CopiedLicense = true;
                }
            }
        }

        if (options.SelfCheck)
            report.CompilationErrors = SelfCheckCompiler.Check(generated, symbols, options.ImplicitUsings, options.RootNamespace, options.FullyQualifiedMetadataPrefixes);

        return report;
    }

    private static string? GetSourceLicensePath(string inputRoot)
    {
        string rootCandidate = Path.GetFullPath(Path.Combine(inputRoot, "..", "..", "LICENSE"));
        if (File.Exists(rootCandidate))
            return rootCandidate;

        string localCandidate = Path.GetFullPath(Path.Combine(inputRoot, "LICENSE"));
        if (File.Exists(localCandidate))
            return localCandidate;

        return null;
    }

    private static string AddGeneratedHeader(string source, BuildOptions options)
    {
        string? customHeader = NormalizeHeader(options.CustomHeader);
        bool includeDefaultAttribution = !options.NoAttribution;

        if (!includeDefaultAttribution && String.IsNullOrWhiteSpace(customHeader))
            return source;

        StringBuilder sb = new();
        if (includeDefaultAttribution)
        {
            sb.Append(DefaultAttributionHeader.TrimEnd());
            sb.Append('\n');
        }

        if (!String.IsNullOrWhiteSpace(customHeader))
        {
            sb.Append(customHeader.TrimEnd());
            sb.Append('\n');
        }

        sb.Append('\n');
        sb.Append(source);
        return sb.ToString();
    }

    private static string? NormalizeHeader(string? header)
    {
        if (String.IsNullOrWhiteSpace(header))
            return null;

        return header
            .Replace("\\r\\n", "\n", StringComparison.Ordinal)
            .Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\\r", "\n", StringComparison.Ordinal);
    }

    private static CompilationUnitSyntax AddAllCandidateUsings(CompilationUnitSyntax unit, HashSet<string> candidateUsings, HashSet<string> implicitUsings)
    {
        HashSet<string> existing = new(unit.Usings
            .Where(u => u.Alias is null && u.StaticKeyword == default)
            .Select(u => u.Name?.ToString() ?? String.Empty)
            .Where(n => !String.IsNullOrWhiteSpace(n))
            .Select(n => n.StartsWith("global::", StringComparison.Ordinal) ? n["global::".Length..] : n),
            StringComparer.Ordinal);

        List<UsingDirectiveSyntax> additions = candidateUsings
            .Where(ns => !implicitUsings.Contains(ns) && !existing.Contains(ns))
            .OrderBy(ns => ns, StringComparer.Ordinal)
            .Select(ns => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(ns)))
            .ToList();

        return additions.Count == 0 ? unit : unit.WithUsings(unit.Usings.AddRange(additions));
    }

    private static Dictionary<string, CompilationUnitSyntax> QualifyMetadataTypeReferences(
        Dictionary<string, CompilationUnitSyntax> allFiles,
        CSharpParseOptions finalParseOptions,
        HashSet<string> implicitUsings,
        HashSet<string> fullyQualifiedMetadataPrefixes)
    {
        Dictionary<string, string> sourceTexts = allFiles.ToDictionary(
            static kv => kv.Key,
            static kv => kv.Value.NormalizeWhitespace(eol: "\n").ToFullString() + "\n",
            StringComparer.Ordinal);

        Dictionary<string, string> rewrittenTexts = QualifyMetadataTypeReferencesInText(sourceTexts, implicitUsings, fullyQualifiedMetadataPrefixes);
        return rewrittenTexts.ToDictionary(
            static kv => kv.Key,
            kv => CSharpSyntaxTree.ParseText(kv.Value, finalParseOptions, kv.Key).GetCompilationUnitRoot(),
            StringComparer.Ordinal);
    }

    private static Dictionary<string, string> QualifyMetadataTypeReferencesInText(
        Dictionary<string, string> sourceTexts,
        HashSet<string> implicitUsings,
        HashSet<string> fullyQualifiedMetadataPrefixes)
    {
        Dictionary<string, Dictionary<TextSpan, string>> editsByPath = sourceTexts.Keys.ToDictionary(
            static path => path,
            static _ => new Dictionary<TextSpan, string>(),
            StringComparer.Ordinal);

        List<HashSet<string>> passSymbols = PreprocessorPruner.CollectBranchActivationSymbolSets(sourceTexts.Values);

        foreach (HashSet<string> symbols in passSymbols)
        {
            CSharpParseOptions passParseOptions = new(languageVersion: LanguageVersion.Preview, preprocessorSymbols: symbols);
            CSharpCompilation compilation = CreateCompilation(sourceTexts, passParseOptions, implicitUsings, out Dictionary<string, SyntaxTree> treeLookup);

            foreach (string path in sourceTexts.Keys)
            {
                SyntaxTree syntaxTree = treeLookup[path];
                SemanticModel semanticModel = compilation.GetSemanticModel(syntaxTree);
                var collector = new MetadataTypeQualificationCollector(semanticModel, compilation.Assembly, fullyQualifiedMetadataPrefixes);
                collector.Visit(syntaxTree.GetCompilationUnitRoot());

                foreach ((TextSpan span, string replacement) in collector.Edits)
                {
                    if (editsByPath[path].TryGetValue(span, out string? existing))
                    {
                        if (!String.Equals(existing, replacement, StringComparison.Ordinal))
                            throw new InvalidOperationException($"Conflicting qualification edits detected for {path} at span {span}.");
                    }
                    else
                    {
                        editsByPath[path][span] = replacement;
                    }
                }
            }
        }

        Dictionary<string, string> rewritten = new(StringComparer.Ordinal);
        foreach ((string path, string source) in sourceTexts)
            rewritten[path] = ApplyTextEdits(source, editsByPath[path]);

        return rewritten;
    }

    private static string ApplyTextEdits(string source, IReadOnlyDictionary<TextSpan, string> edits)
    {
        if (edits.Count == 0)
            return source;

        StringBuilder sb = new(source);
        foreach ((TextSpan span, string replacement) in edits.OrderByDescending(kv => kv.Key.Start))
            sb.Remove(span.Start, span.Length).Insert(span.Start, replacement);

        return sb.ToString();
    }

    private static CSharpCompilation CreateCompilation(
        Dictionary<string, CompilationUnitSyntax> allFiles,
        CSharpParseOptions parseOptions,
        HashSet<string> implicitUsings,
        out Dictionary<string, SyntaxTree> treeLookup,
        bool includeUnnecessaryUsingDiagnostics = false)
    {
        treeLookup = new Dictionary<string, SyntaxTree>(StringComparer.Ordinal);
        List<SyntaxTree> trees = [];

        if (implicitUsings.Count > 0)
        {
            StringBuilder implicitSb = new();
            foreach (string ns in implicitUsings.OrderBy(x => x, StringComparer.Ordinal))
                implicitSb.AppendLine($"global using {ns};");
            trees.Add(CSharpSyntaxTree.ParseText(implicitSb.ToString(), parseOptions, "__implicit_usings.g.cs"));
        }

        foreach ((string path, CompilationUnitSyntax unit) in allFiles)
        {
            SyntaxTree tree = CSharpSyntaxTree.Create(unit, parseOptions, path, Encoding.UTF8);
            trees.Add(tree);
            treeLookup[path] = tree;
        }

        CSharpCompilationOptions compilationOptions = new(OutputKind.DynamicallyLinkedLibrary);
        if (includeUnnecessaryUsingDiagnostics)
        {
            compilationOptions = compilationOptions.WithSpecificDiagnosticOptions(new Dictionary<string, ReportDiagnostic>
            {
                ["CS8019"] = ReportDiagnostic.Warn
            });
        }

        return CSharpCompilation.Create(
            "__internalization",
            trees,
            CreateMetadataReferences(),
            compilationOptions);
    }

    private static CSharpCompilation CreateCompilation(
        IReadOnlyDictionary<string, string> sourceTexts,
        CSharpParseOptions parseOptions,
        HashSet<string> implicitUsings,
        out Dictionary<string, SyntaxTree> treeLookup,
        bool includeUnnecessaryUsingDiagnostics = false)
    {
        treeLookup = new Dictionary<string, SyntaxTree>(StringComparer.Ordinal);
        List<SyntaxTree> trees = [];

        if (implicitUsings.Count > 0)
        {
            StringBuilder implicitSb = new();
            foreach (string ns in implicitUsings.OrderBy(x => x, StringComparer.Ordinal))
                implicitSb.AppendLine($"global using {ns};");
            trees.Add(CSharpSyntaxTree.ParseText(implicitSb.ToString(), parseOptions, "__implicit_usings.g.cs"));
        }

        foreach ((string path, string source) in sourceTexts)
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(source, parseOptions, path, Encoding.UTF8);
            trees.Add(tree);
            treeLookup[path] = tree;
        }

        CSharpCompilationOptions compilationOptions = new(OutputKind.DynamicallyLinkedLibrary);
        if (includeUnnecessaryUsingDiagnostics)
        {
            compilationOptions = compilationOptions.WithSpecificDiagnosticOptions(new Dictionary<string, ReportDiagnostic>
            {
                ["CS8019"] = ReportDiagnostic.Warn
            });
        }

        return CSharpCompilation.Create(
            "__internalization",
            trees,
            CreateMetadataReferences(),
            compilationOptions);
    }

    private static List<MetadataReference> CreateMetadataReferences()
    {
        List<MetadataReference> references = [];
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (!String.IsNullOrWhiteSpace(tpa))
        {
            foreach (string assemblyPath in tpa.Split(Path.PathSeparator))
                references.Add(MetadataReference.CreateFromFile(assemblyPath));
        }

        return references;
    }

    private static Dictionary<string, HashSet<int>> FindUnnecessaryUsings(
        Dictionary<string, CompilationUnitSyntax> allFiles,
        CSharpParseOptions parseOptions,
        HashSet<string> implicitUsings)
    {
        CSharpCompilation compilation = CreateCompilation(allFiles, parseOptions, implicitUsings, out Dictionary<string, SyntaxTree> treeLookup, includeUnnecessaryUsingDiagnostics: true);

        Dictionary<string, HashSet<int>> result = new(StringComparer.Ordinal);
        ImmutableArray<Diagnostic> diagnostics = compilation.GetDiagnostics();

        foreach (Diagnostic diag in diagnostics)
        {
            if (diag.Id != "CS8019")
                continue;

            string filePath = diag.Location.SourceTree?.FilePath ?? String.Empty;
            if (String.IsNullOrEmpty(filePath) || !treeLookup.ContainsKey(filePath))
                continue;

            if (!result.TryGetValue(filePath, out HashSet<int>? spans))
            {
                spans = [];
                result[filePath] = spans;
            }

            spans.Add(diag.Location.SourceSpan.Start);
        }

        return result;
    }

    private static CompilationUnitSyntax StripUnnecessaryUsings(
        CompilationUnitSyntax unit,
        HashSet<int> unnecessarySpanStarts,
        HashSet<string> implicitUsings)
    {
        SyntaxList<UsingDirectiveSyntax> filtered = new(unit.Usings.Where(u =>
        {
            if (u.Alias is not null || u.StaticKeyword != default)
                return true;

            string? name = u.Name?.ToString();
            if (String.IsNullOrWhiteSpace(name))
                return true;

            string normalized = name.StartsWith("global::", StringComparison.Ordinal) ? name["global::".Length..] : name;

            if (implicitUsings.Contains(normalized))
                return false;

            return !unnecessarySpanStarts.Contains(u.SpanStart);
        }));

        return unit.WithUsings(filtered);
    }

    private static HashSet<string> DiscoverSourceImplicitUsings(string inputRoot)
    {
        HashSet<string> result = new(StringComparer.Ordinal);
        string? csproj = Directory.GetFiles(inputRoot, "*.csproj", SearchOption.TopDirectoryOnly).FirstOrDefault()
                         ?? Directory.GetFiles(Path.GetDirectoryName(inputRoot) ?? inputRoot, "*.csproj", SearchOption.TopDirectoryOnly).FirstOrDefault();

        bool hasImplicitUsings = false;
        if (csproj is not null)
        {
            string content = File.ReadAllText(csproj);
            hasImplicitUsings = content.Contains("<ImplicitUsings>enable</ImplicitUsings>", StringComparison.OrdinalIgnoreCase);
        }

        if (hasImplicitUsings)
        {
            result.Add("System");
            result.Add("System.Collections.Generic");
            result.Add("System.IO");
            result.Add("System.Linq");
            result.Add("System.Net.Http");
            result.Add("System.Threading");
            result.Add("System.Threading.Tasks");
        }

        return result;
    }

    private static void PrintUsage()
    {
        Console.WriteLine("""
Usage:
  FastCloner.Internalization.Builder --root-namespace <ns> --output <path> [options]

Required:
  --root-namespace <ns>                     Target root namespace for generated code.
  --output <path>                           Output directory for generated files.

Optional:
  --input-root <path>                       FastCloner runtime source root (defaults to ../FastCloner).
  --preprocessor <k=v;k2=v2>                Per-symbol preprocessor overrides.
                                            Example:
                                              MODERN=true;NET8_0_OR_GREATER=true
                                              MODERN=true;SOMETHING=random_text
                                            Default replacements:
                                              MODERN_10=NET10_0_OR_GREATER
                                            Special values:
                                              true / false (recognized booleans)
                                            Non-boolean values are used as direct token replacement in #if expressions.
  --implicit-usings <ns1;ns2;...>          List of namespaces assumed implicit in target project.
                                            When provided, matching global usings are omitted from generated code.
  --fqn <prefix1|prefix2|...>               Fully qualify matching external metadata types.
                                            Examples:
                                              all
                                              System
                                              System|System.Collections
  --visibility <public|internal>            Top-level visibility rewrite mode (default: internal).
  --public-api <none|fastcloner|extensions|behaviors|all>
                                            Exceptions to keep public when visibility=internal (default: none).
  --runtime-only <true|false>               Include only runtime sources (default: true).
  --no-license                              Do not copy LICENSE file to output root.
  --no-attribution                          Do not emit default attribution header in generated .cs files.
  --header <text>                           Custom header/banner inserted under default attribution header.
  --dry-run                                 Print generation plan, do not write files.
  --self-check                              Compile generated tree and report compile errors.
""");
    }
}

internal enum VisibilityMode
{
    Public,
    Internal
}

internal enum PublicApiMode
{
    None,
    FastCloner,
    Extensions,
    Behaviors,
    All
}

internal sealed class BuildOptions
{
    public const string FullyQualifyAll = "all";

    private static readonly IReadOnlyDictionary<string, string> DefaultPreprocessor = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["MODERN_10"] = "NET10_0_OR_GREATER"
    };

    public required string RootNamespace { get; init; }
    public required string Output { get; init; }
    public required string InputRoot { get; init; }
    public required Dictionary<string, string> Preprocessor { get; init; }
    public required HashSet<string> ImplicitUsings { get; init; }
    public required HashSet<string> FullyQualifiedMetadataPrefixes { get; init; }
    public required VisibilityMode Visibility { get; init; }
    public required PublicApiMode PublicApi { get; init; }
    public required bool RuntimeOnly { get; init; }
    public required bool NoLicense { get; init; }
    public required bool NoAttribution { get; init; }
    public required string? CustomHeader { get; init; }
    public required bool DryRun { get; init; }
    public required bool SelfCheck { get; init; }

    public static BuildOptions? Parse(string[] args)
    {
        Dictionary<string, string?> kv = ParseArgs(args);
        if (kv.Count == 0 || kv.ContainsKey("--help") || kv.ContainsKey("-h"))
            return null;

        if (!kv.TryGetValue("--root-namespace", out string? rootNs) || String.IsNullOrWhiteSpace(rootNs))
            throw new ArgumentException("--root-namespace is required.");
        if (!kv.TryGetValue("--output", out string? output) || String.IsNullOrWhiteSpace(output))
            throw new ArgumentException("--output is required.");

        string defaultInputRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "FastCloner"));
        string inputRoot = Get(kv, "--input-root", defaultInputRoot);
        Dictionary<string, string> preprocessor = ParsePreprocessor(Get(kv, "--preprocessor", String.Empty));
        HashSet<string> implicitUsings = ParseNamespaceList(Get(kv, "--implicit-usings", String.Empty));
        HashSet<string> fullyQualifiedMetadataPrefixes = ParseFqnPrefixes(Get(kv, "--fqn", String.Empty));

        VisibilityMode visibility = ParseEnum(Get(kv, "--visibility", "internal"), new Dictionary<string, VisibilityMode>(StringComparer.OrdinalIgnoreCase)
        {
            ["public"] = VisibilityMode.Public,
            ["internal"] = VisibilityMode.Internal
        }, "--visibility");

        PublicApiMode publicApi = ParseEnum(Get(kv, "--public-api", "none"), new Dictionary<string, PublicApiMode>(StringComparer.OrdinalIgnoreCase)
        {
            ["none"] = PublicApiMode.None,
            ["fastcloner"] = PublicApiMode.FastCloner,
            ["extensions"] = PublicApiMode.Extensions,
            ["behaviors"] = PublicApiMode.Behaviors,
            ["all"] = PublicApiMode.All
        }, "--public-api");

        bool runtimeOnly = ParseBool(Get(kv, "--runtime-only", "true"), "--runtime-only");
        bool noLicense = kv.ContainsKey("--no-license");
        bool noAttribution = kv.ContainsKey("--no-attribution");
        string? customHeader = kv.TryGetValue("--header", out string? headerValue) && !String.IsNullOrWhiteSpace(headerValue)
            ? headerValue
            : null;
        bool dryRun = kv.ContainsKey("--dry-run");
        bool selfCheck = kv.ContainsKey("--self-check");

        return new BuildOptions
        {
            RootNamespace = rootNs.Trim(),
            Output = Path.GetFullPath(output),
            InputRoot = Path.GetFullPath(inputRoot),
            Preprocessor = preprocessor,
            ImplicitUsings = implicitUsings,
            FullyQualifiedMetadataPrefixes = fullyQualifiedMetadataPrefixes,
            Visibility = visibility,
            PublicApi = publicApi,
            RuntimeOnly = runtimeOnly,
            NoLicense = noLicense,
            NoAttribution = noAttribution,
            CustomHeader = customHeader,
            DryRun = dryRun,
            SelfCheck = selfCheck
        };
    }

    public HashSet<string> GetPreprocessorSymbols()
    {
        HashSet<string> symbols = new(StringComparer.Ordinal);
        foreach ((string key, string value) in Preprocessor)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "true"))
                symbols.Add(key);
            else if (TryGetSinglePreprocessorIdentifier(value, out string referencedSymbol))
                symbols.Add(referencedSymbol);
        }

        return symbols;
    }

    private static bool TryGetSinglePreprocessorIdentifier(string value, out string identifier)
    {
        identifier = String.Empty;
        if (String.IsNullOrWhiteSpace(value))
            return false;

        ExpressionSyntax expression = SyntaxFactory.ParseExpression(value);
        if (expression.ContainsDiagnostics)
            return false;

        if (expression is not IdentifierNameSyntax identifierName)
            return false;

        if (!String.Equals(identifierName.Identifier.ValueText, value, StringComparison.Ordinal))
            return false;

        if (identifierName.GetLastToken().TrailingTrivia.Count > 0 || identifierName.GetFirstToken().LeadingTrivia.Count > 0)
        {
            return false;
        }

        identifier = identifierName.Identifier.ValueText;
        return true;
    }

    private static Dictionary<string, string> ParsePreprocessor(string raw)
    {
        Dictionary<string, string> map = new(DefaultPreprocessor, StringComparer.Ordinal);
        if (String.IsNullOrWhiteSpace(raw))
            return map;

        foreach (string pair in raw.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            int eq = pair.IndexOf('=');
            if (eq <= 0 || eq == pair.Length - 1)
                throw new ArgumentException($"Invalid --preprocessor entry '{pair}'. Expected KEY=VALUE.");

            string key = pair[..eq].Trim();
            string value = pair[(eq + 1)..].Trim();
            if (key.Length == 0 || value.Length == 0)
                throw new ArgumentException($"Invalid --preprocessor entry '{pair}'. Empty key/value.");

            map[key] = value;
        }

        return map;
    }

    private static HashSet<string> ParseNamespaceList(string raw)
    {
        HashSet<string> set = new(StringComparer.Ordinal);
        if (String.IsNullOrWhiteSpace(raw))
            return set;

        foreach (string value in raw.Split([';', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (value.Length == 0)
                continue;
            set.Add(value.StartsWith("global::", StringComparison.Ordinal) ? value["global::".Length..] : value);
        }

        return set;
    }

    private static HashSet<string> ParseFqnPrefixes(string raw)
    {
        HashSet<string> set = new(StringComparer.Ordinal);
        if (String.IsNullOrWhiteSpace(raw))
            return set;

        foreach (string value in raw.Split(['|', ';', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            string normalized = value.StartsWith("global::", StringComparison.Ordinal) ? value["global::".Length..] : value;
            if (!String.IsNullOrWhiteSpace(normalized))
                set.Add(normalized);
        }

        return set;
    }

    public static bool ShouldFullyQualifyMetadataType(ITypeSymbol typeSymbol, IAssemblySymbol generatedAssembly, HashSet<string> fullyQualifiedMetadataPrefixes)
    {
        if (fullyQualifiedMetadataPrefixes.Count == 0)
            return false;
        if (SymbolEqualityComparer.Default.Equals(typeSymbol.ContainingAssembly, generatedAssembly))
            return false;

        if (fullyQualifiedMetadataPrefixes.Contains(FullyQualifyAll))
            return true;

        string displayName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string normalizedDisplayName = displayName.StartsWith("global::", StringComparison.Ordinal) ? displayName["global::".Length..] : displayName;
        return fullyQualifiedMetadataPrefixes.Any(prefix => normalizedDisplayName.Equals(prefix, StringComparison.Ordinal) ||
                                                            normalizedDisplayName.StartsWith(prefix + ".", StringComparison.Ordinal));
    }

    private static Dictionary<string, string?> ParseArgs(string[] args)
    {
        Dictionary<string, string?> parsed = new(StringComparer.OrdinalIgnoreCase);
        for (int i = 0; i < args.Length; i++)
        {
            string current = args[i];
            if (!current.StartsWith('-'))
                continue;

            int equalsIndex = current.IndexOf('=');
            if (equalsIndex > 0)
            {
                string key = current[..equalsIndex];
                string value = current[(equalsIndex + 1)..];
                parsed[key] = value.Length == 0 ? null : value;
                continue;
            }

            if (i + 1 < args.Length && !args[i + 1].StartsWith('-'))
            {
                parsed[current] = args[i + 1];
                i++;
            }
            else
            {
                parsed[current] = null;
            }
        }

        return parsed;
    }

    private static string Get(Dictionary<string, string?> args, string key, string defaultValue)
    {
        return args.TryGetValue(key, out string? value) && !String.IsNullOrWhiteSpace(value)
            ? value
            : defaultValue;
    }

    private static T ParseEnum<T>(string value, IReadOnlyDictionary<string, T> map, string optionName) where T : struct
    {
        if (map.TryGetValue(value, out T mode))
            return mode;

        throw new ArgumentException($"Invalid value '{value}' for {optionName}.");
    }

    private static bool ParseBool(string value, string optionName)
    {
        if (Boolean.TryParse(value, out bool parsed))
            return parsed;

        throw new ArgumentException($"Invalid boolean value '{value}' for {optionName}.");
    }
}

internal sealed class BuildReport(BuildOptions options, int discoveredFiles)
{
    public BuildOptions Options { get; } = options;
    public int DiscoveredFiles { get; } = discoveredFiles;
    public int WrittenFiles { get; set; }
    public int NamespaceRewrites { get; set; }
    public int VisibilityRewrites { get; set; }
    public int PrunedDirectiveLines { get; set; }
    public int PrunedBranchLines { get; set; }
    public bool CopiedLicense { get; set; }
    public int CompilationErrors { get; set; }
    public bool HasErrors => CompilationErrors > 0;

    public void Print()
    {
        Console.WriteLine("FastCloner internalization builder report");
        Console.WriteLine($"  input-root: {Options.InputRoot}");
        Console.WriteLine($"  output: {Options.Output}");
        Console.WriteLine($"  preprocessor: {(Options.Preprocessor.Count == 0 ? "(none)" : String.Join("; ", Options.Preprocessor.Select(kv => $"{kv.Key}={kv.Value}")))}");
        Console.WriteLine($"  implicit-usings: {(Options.ImplicitUsings.Count == 0 ? "(none)" : String.Join("; ", Options.ImplicitUsings.OrderBy(x => x, StringComparer.Ordinal)))}");
        Console.WriteLine($"  visibility: {Options.Visibility} (public-api: {Options.PublicApi})");
        Console.WriteLine($"  attribution header: {(!Options.NoAttribution ? "default" : "disabled")}");
        Console.WriteLine($"  custom header: {(String.IsNullOrWhiteSpace(Options.CustomHeader) ? "(none)" : "provided")}");
        Console.WriteLine($"  discovered files: {DiscoveredFiles}");
        Console.WriteLine($"  written files: {(Options.DryRun ? 0 : WrittenFiles)}");
        Console.WriteLine($"  namespace rewrites: {NamespaceRewrites}");
        Console.WriteLine($"  visibility rewrites: {VisibilityRewrites}");
        Console.WriteLine($"  pruned directive lines: {PrunedDirectiveLines}");
        Console.WriteLine($"  pruned branch lines: {PrunedBranchLines}");
        Console.WriteLine($"  copied license: {CopiedLicense}");
        if (Options.SelfCheck)
            Console.WriteLine($"  compile errors: {CompilationErrors}");
    }
}

internal static class RuntimeManifest
{
    public static string[] DiscoverRuntimeFiles(string inputRoot, bool runtimeOnly)
    {
        IEnumerable<string> files = Directory
            .GetFiles(inputRoot, "*.cs", SearchOption.AllDirectories)
            .Where(static path => !path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase))
            .Where(static path => !path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase));

        if (runtimeOnly)
        {
            files = files
                .Where(static path => !path.EndsWith("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase))
                .Where(path =>
                {
                    string relative = Path.GetRelativePath(inputRoot, path).Replace('\\', '/');
                    return relative.StartsWith("Code/", StringComparison.Ordinal) ||
                           relative.Equals("FastCloner.cs", StringComparison.OrdinalIgnoreCase);
                });
        }

        return files
            .OrderBy(path => Path.GetRelativePath(inputRoot, path), StringComparer.Ordinal)
            .ToArray();
    }
}

internal readonly record struct PruneResult(string Text, int PrunedDirectiveLines, int PrunedBranchLines);

internal static class PreprocessorPruner
{
    public static PruneResult Transform(string source, IReadOnlyDictionary<string, string> replacements)
    {
        string[] lines = source.Replace("\r\n", "\n").Split('\n');
        string[] rewrittenLines = new string[lines.Length];
        bool allResolvable = true;

        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            if (TryParseDirective(line.TrimStart(), out string directive, out string expression) &&
                (directive == "if" || directive == "elif"))
            {
                string replacedExpression = ReplaceSymbols(expression, replacements);
                if (TryEvaluateBoolExpression(replacedExpression, out _))
                {
                    rewrittenLines[i] = ReplaceDirectiveExpression(line, directive, replacedExpression);
                }
                else
                {
                    allResolvable = false;
                    rewrittenLines[i] = ReplaceDirectiveExpression(line, directive, replacedExpression);
                }
            }
            else
            {
                rewrittenLines[i] = line;
            }
        }

        if (!allResolvable)
            return new PruneResult(String.Join('\n', rewrittenLines), 0, 0);

        return PruneResolved(String.Join('\n', rewrittenLines));
    }

    public static HashSet<string> CollectReferencedIdentifiers(string source)
    {
        HashSet<string> identifiers = new(StringComparer.Ordinal);
        foreach (string line in source.Replace("\r\n", "\n").Split('\n'))
        {
            string trimmed = line.TrimStart();
            if (!TryParseDirective(trimmed, out string directive, out string expression) || directive is not ("if" or "elif"))
                continue;

            ExpressionSyntax parsed = SyntaxFactory.ParseExpression(expression);
            if (parsed.ContainsDiagnostics)
                continue;

            foreach (IdentifierNameSyntax identifier in parsed.DescendantNodesAndSelf().OfType<IdentifierNameSyntax>())
                identifiers.Add(identifier.Identifier.ValueText);
        }

        return identifiers;
    }

    public static List<HashSet<string>> CollectBranchActivationSymbolSets(IEnumerable<string> sources)
    {
        Dictionary<string, HashSet<string>> unique = new(StringComparer.Ordinal);

        foreach (string source in sources)
        {
            foreach (HashSet<string> symbols in CollectBranchActivationSymbolSets(source))
            {
                string key = symbols.Count == 0 ? String.Empty : String.Join("|", symbols.OrderBy(x => x, StringComparer.Ordinal));
                if (!unique.ContainsKey(key))
                    unique[key] = symbols;
            }
        }

        return unique.Count == 0
            ? [new HashSet<string>(StringComparer.Ordinal)]
            : unique.Values.ToList();
    }

    private static IEnumerable<HashSet<string>> CollectBranchActivationSymbolSets(string source)
    {
        Stack<BranchExplorationFrame> stack = new();

        foreach (string line in source.Replace("\r\n", "\n").Split('\n'))
        {
            string trimmed = line.TrimStart();
            if (!TryParseDirective(trimmed, out string directive, out string expression))
                continue;

            switch (directive)
            {
                case "if":
                {
                    BoolExpr condition = ParseBoolExpr(expression);
                    BoolExpr parentCondition = stack.Count == 0 ? BoolExpr.True : stack.Peek().CurrentBranchCondition;
                    BoolExpr branchCondition = BoolExpr.And(parentCondition, condition);
                    stack.Push(new BranchExplorationFrame(parentCondition, branchCondition, [condition]));
                    break;
                }
                case "elif":
                {
                    BranchExplorationFrame frame = stack.Pop();
                    BoolExpr condition = ParseBoolExpr(expression);
                    BoolExpr branchCondition = BoolExpr.And(frame.ParentCondition, BoolExpr.And(BuildNoPreviousBranchMatched(frame.BranchConditions), condition));
                    frame.BranchConditions.Add(condition);
                    frame.CurrentBranchCondition = branchCondition;
                    stack.Push(frame);
                    break;
                }
                case "else":
                {
                    BranchExplorationFrame frame = stack.Pop();
                    frame.CurrentBranchCondition = BoolExpr.And(frame.ParentCondition, BuildNoPreviousBranchMatched(frame.BranchConditions));
                    stack.Push(frame);
                    break;
                }
                case "endif":
                    _ = stack.Pop();
                    break;
            }

            if (directive is "if" or "elif" or "else")
            {
                BranchExplorationFrame current = stack.Peek();
                SymbolAssignment? assignment = Solve(current.CurrentBranchCondition, desired: true);
                if (assignment is not null)
                    yield return assignment.TrueSymbols;
            }
        }
    }

    private static BoolExpr BuildNoPreviousBranchMatched(IEnumerable<BoolExpr> branchConditions)
    {
        BoolExpr result = BoolExpr.True;
        foreach (BoolExpr condition in branchConditions)
            result = BoolExpr.And(result, BoolExpr.Not(condition));

        return result;
    }

    private static BoolExpr ParseBoolExpr(string expression)
    {
        ExpressionSyntax parsed = SyntaxFactory.ParseExpression(expression);
        if (parsed.ContainsDiagnostics)
            return BoolExpr.False;

        return ConvertBoolExpr(parsed);
    }

    private static BoolExpr ConvertBoolExpr(ExpressionSyntax expression)
    {
        return expression switch
        {
            ParenthesizedExpressionSyntax paren => ConvertBoolExpr(paren.Expression),
            PrefixUnaryExpressionSyntax { RawKind: (int)SyntaxKind.LogicalNotExpression } unary => BoolExpr.Not(ConvertBoolExpr(unary.Operand)),
            BinaryExpressionSyntax { RawKind: (int)SyntaxKind.LogicalAndExpression } binary => BoolExpr.And(ConvertBoolExpr(binary.Left), ConvertBoolExpr(binary.Right)),
            BinaryExpressionSyntax { RawKind: (int)SyntaxKind.LogicalOrExpression } binary => BoolExpr.Or(ConvertBoolExpr(binary.Left), ConvertBoolExpr(binary.Right)),
            LiteralExpressionSyntax literal when literal.IsKind(SyntaxKind.TrueLiteralExpression) => BoolExpr.True,
            LiteralExpressionSyntax literal when literal.IsKind(SyntaxKind.FalseLiteralExpression) => BoolExpr.False,
            IdentifierNameSyntax identifier => new BoolExpr.Symbol(identifier.Identifier.ValueText),
            _ => BoolExpr.False
        };
    }

    private static SymbolAssignment? Solve(BoolExpr expression, bool desired)
    {
        return expression switch
        {
            BoolExpr.Literal literal => literal.Value == desired ? SymbolAssignment.Empty() : null,
            BoolExpr.Symbol symbol => desired ? SymbolAssignment.WithTrue(symbol.Name) : SymbolAssignment.WithFalse(symbol.Name),
            BoolExpr.NotExpr not => Solve(not.Operand, !desired),
            BoolExpr.AndExpr and => desired
                ? Merge(Solve(and.Left, true), Solve(and.Right, true))
                : ChooseBetter(Solve(and.Left, false), Solve(and.Right, false)),
            BoolExpr.OrExpr or => desired
                ? ChooseBetter(Solve(or.Left, true), Solve(or.Right, true))
                : Merge(Solve(or.Left, false), Solve(or.Right, false)),
            _ => null
        };
    }

    private static SymbolAssignment? Merge(SymbolAssignment? left, SymbolAssignment? right)
    {
        if (left is null || right is null)
            return null;
        if (left.TrueSymbols.Overlaps(right.FalseSymbols) || left.FalseSymbols.Overlaps(right.TrueSymbols))
            return null;

        return new SymbolAssignment(
            [.. left.TrueSymbols, .. right.TrueSymbols],
            [.. left.FalseSymbols, .. right.FalseSymbols]);
    }

    private static SymbolAssignment? ChooseBetter(SymbolAssignment? first, SymbolAssignment? second)
    {
        if (first is null)
            return second;
        if (second is null)
            return first;

        int firstTrueCount = first.TrueSymbols.Count;
        int secondTrueCount = second.TrueSymbols.Count;
        if (firstTrueCount != secondTrueCount)
            return firstTrueCount < secondTrueCount ? first : second;

        int firstSpecifiedCount = firstTrueCount + first.FalseSymbols.Count;
        int secondSpecifiedCount = secondTrueCount + second.FalseSymbols.Count;
        if (firstSpecifiedCount != secondSpecifiedCount)
            return firstSpecifiedCount < secondSpecifiedCount ? first : second;

        string firstKey = String.Join("|", first.TrueSymbols.OrderBy(x => x, StringComparer.Ordinal));
        string secondKey = String.Join("|", second.TrueSymbols.OrderBy(x => x, StringComparer.Ordinal));
        return StringComparer.Ordinal.Compare(firstKey, secondKey) <= 0 ? first : second;
    }

    private sealed class BranchExplorationFrame(BoolExpr parentCondition, BoolExpr currentBranchCondition, List<BoolExpr> branchConditions)
    {
        public BoolExpr ParentCondition { get; } = parentCondition;
        public BoolExpr CurrentBranchCondition { get; set; } = currentBranchCondition;
        public List<BoolExpr> BranchConditions { get; } = branchConditions;
    }

    private sealed class SymbolAssignment(HashSet<string> trueSymbols, HashSet<string> falseSymbols)
    {
        public HashSet<string> TrueSymbols { get; } = trueSymbols;
        public HashSet<string> FalseSymbols { get; } = falseSymbols;

        public static SymbolAssignment Empty() => new(new HashSet<string>(StringComparer.Ordinal), new HashSet<string>(StringComparer.Ordinal));
        public static SymbolAssignment WithTrue(string name) => new(new HashSet<string>(StringComparer.Ordinal) { name }, new HashSet<string>(StringComparer.Ordinal));
        public static SymbolAssignment WithFalse(string name) => new(new HashSet<string>(StringComparer.Ordinal), new HashSet<string>(StringComparer.Ordinal) { name });
    }

    private abstract record BoolExpr
    {
        public static readonly Literal True = new(true);
        public static readonly Literal False = new(false);

        public static BoolExpr Not(BoolExpr operand) => operand switch
        {
            Literal literal => literal.Value ? False : True,
            NotExpr not => not.Operand,
            _ => new NotExpr(operand)
        };

        public static BoolExpr And(BoolExpr left, BoolExpr right)
        {
            if (left == False || right == False)
                return False;
            if (left == True)
                return right;
            if (right == True)
                return left;
            return new AndExpr(left, right);
        }

        public static BoolExpr Or(BoolExpr left, BoolExpr right)
        {
            if (left == True || right == True)
                return True;
            if (left == False)
                return right;
            if (right == False)
                return left;
            return new OrExpr(left, right);
        }

        public sealed record Literal(bool Value) : BoolExpr;
        public sealed record Symbol(string Name) : BoolExpr;
        public sealed record NotExpr(BoolExpr Operand) : BoolExpr;
        public sealed record AndExpr(BoolExpr Left, BoolExpr Right) : BoolExpr;
        public sealed record OrExpr(BoolExpr Left, BoolExpr Right) : BoolExpr;
    }

    private static PruneResult PruneResolved(string source)
    {
        string[] lines = source.Split('\n');
        List<string> output = new(lines.Length);
        Stack<ConditionalFrame> stack = new();
        bool active = true;
        int prunedDirectives = 0;
        int prunedBranchLines = 0;

        foreach (string line in lines)
        {
            string trimmed = line.TrimStart();
            if (!trimmed.StartsWith('#'))
            {
                if (active)
                    output.Add(line);
                else
                    prunedBranchLines++;
                continue;
            }

            if (!TryParseDirective(trimmed, out string directive, out string expression))
            {
                if (active)
                    output.Add(line);
                continue;
            }

            prunedDirectives++;

            switch (directive)
            {
                case "if":
                {
                    bool parentActive = active;
                    bool currentActive = parentActive && SymbolExpressionEvaluator.Evaluate(expression);
                    stack.Push(new ConditionalFrame(parentActive, currentActive, currentActive));
                    active = currentActive;
                    break;
                }
                case "elif":
                {
                    ConditionalFrame frame = stack.Pop();
                    bool currentActive = frame.ParentActive &&
                                         !frame.BranchTaken &&
                                         SymbolExpressionEvaluator.Evaluate(expression);
                    stack.Push(frame with { BranchTaken = frame.BranchTaken || currentActive, CurrentActive = currentActive });
                    active = currentActive;
                    break;
                }
                case "else":
                {
                    ConditionalFrame frame = stack.Pop();
                    bool currentActive = frame.ParentActive && !frame.BranchTaken;
                    stack.Push(frame with { BranchTaken = true, CurrentActive = currentActive });
                    active = currentActive;
                    break;
                }
                case "endif":
                {
                    _ = stack.Pop();
                    active = stack.Count == 0 || stack.Peek().CurrentActive;
                    break;
                }
            }
        }

        string prunedText = String.Join('\n', output);
        return new PruneResult(prunedText, prunedDirectives, prunedBranchLines);
    }

    private static bool TryEvaluateBoolExpression(string expression, out bool result)
    {
        try
        {
            result = SymbolExpressionEvaluator.Evaluate(expression);
            return true;
        }
        catch
        {
            result = false;
            return false;
        }
    }

    private static string ReplaceDirectiveExpression(string originalLine, string directive, string newExpression)
    {
        int hashIndex = originalLine.IndexOf('#');
        if (hashIndex < 0)
            return originalLine;

        string indentation = originalLine[..hashIndex];
        return $"{indentation}#{directive} {newExpression}";
    }

    private static string ReplaceSymbols(string expression, IReadOnlyDictionary<string, string> replacements)
    {
        StringBuilder sb = new(expression.Length);
        for (int i = 0; i < expression.Length; i++)
        {
            char c = expression[i];
            if (Char.IsLetterOrDigit(c) || c == '_')
            {
                int start = i;
                while (i + 1 < expression.Length && (Char.IsLetterOrDigit(expression[i + 1]) || expression[i + 1] == '_'))
                    i++;

                string symbol = expression[start..(i + 1)];
                if (replacements.TryGetValue(symbol, out string? replacement))
                    sb.Append(replacement);
                else
                    sb.Append(symbol);
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }

    private static bool TryParseDirective(string trimmedLine, out string directive, out string expression)
    {
        directive = String.Empty;
        expression = String.Empty;

        if (!trimmedLine.StartsWith('#'))
            return false;

        string body = trimmedLine[1..].Trim();
        if (body.StartsWith("if ", StringComparison.Ordinal))
        {
            directive = "if";
            expression = body[3..].Trim();
            return true;
        }
        if (body.StartsWith("elif ", StringComparison.Ordinal))
        {
            directive = "elif";
            expression = body[5..].Trim();
            return true;
        }
        if (body.Equals("else", StringComparison.Ordinal))
        {
            directive = "else";
            return true;
        }
        if (body.Equals("endif", StringComparison.Ordinal))
        {
            directive = "endif";
            return true;
        }

        return false;
    }

    private readonly record struct ConditionalFrame(bool ParentActive, bool BranchTaken, bool CurrentActive);
}

internal static class SymbolExpressionEvaluator
{
    public static bool Evaluate(string expression)
    {
        if (String.IsNullOrWhiteSpace(expression))
            return false;

        List<Token> tokens = Tokenize(expression);
        int index = 0;
        bool result = ParseOr(tokens, ref index);
        if (index != tokens.Count)
            throw new InvalidOperationException($"Unexpected token in preprocessor expression: '{tokens[index].Value}'.");
        return result;
    }

    private static bool ParseOr(List<Token> tokens, ref int index)
    {
        bool left = ParseAnd(tokens, ref index);
        while (Match(tokens, ref index, TokenType.Or))
            left = left || ParseAnd(tokens, ref index);
        return left;
    }

    private static bool ParseAnd(List<Token> tokens, ref int index)
    {
        bool left = ParseUnary(tokens, ref index);
        while (Match(tokens, ref index, TokenType.And))
            left = left && ParseUnary(tokens, ref index);
        return left;
    }

    private static bool ParseUnary(List<Token> tokens, ref int index)
    {
        if (Match(tokens, ref index, TokenType.Not))
            return !ParseUnary(tokens, ref index);
        return ParsePrimary(tokens, ref index);
    }

    private static bool ParsePrimary(List<Token> tokens, ref int index)
    {
        if (Match(tokens, ref index, TokenType.OpenParen))
        {
            bool value = ParseOr(tokens, ref index);
            Expect(tokens, ref index, TokenType.CloseParen);
            return value;
        }

        Token token = Expect(tokens, ref index, TokenType.Identifier);
        if (token.Value.Equals("true", StringComparison.OrdinalIgnoreCase))
            return true;
        if (token.Value.Equals("false", StringComparison.OrdinalIgnoreCase))
            return false;

        throw new InvalidOperationException($"Unresolved symbol '{token.Value}' in preprocessor expression.");
    }

    private static Token Expect(List<Token> tokens, ref int index, TokenType type)
    {
        if (index >= tokens.Count || tokens[index].Type != type)
            throw new InvalidOperationException($"Unexpected token while parsing preprocessor expression. Expected {type}.");

        return tokens[index++];
    }

    private static bool Match(List<Token> tokens, ref int index, TokenType type)
    {
        if (index < tokens.Count && tokens[index].Type == type)
        {
            index++;
            return true;
        }
        return false;
    }

    private static List<Token> Tokenize(string expression)
    {
        List<Token> tokens = [];
        for (int i = 0; i < expression.Length; i++)
        {
            char c = expression[i];
            if (Char.IsWhiteSpace(c))
                continue;

            if (c == '!' )
            {
                tokens.Add(new Token(TokenType.Not, "!"));
                continue;
            }
            if (c == '&' && i + 1 < expression.Length && expression[i + 1] == '&')
            {
                tokens.Add(new Token(TokenType.And, "&&"));
                i++;
                continue;
            }
            if (c == '|' && i + 1 < expression.Length && expression[i + 1] == '|')
            {
                tokens.Add(new Token(TokenType.Or, "||"));
                i++;
                continue;
            }
            if (c == '(')
            {
                tokens.Add(new Token(TokenType.OpenParen, "("));
                continue;
            }
            if (c == ')')
            {
                tokens.Add(new Token(TokenType.CloseParen, ")"));
                continue;
            }

            if (Char.IsLetterOrDigit(c) || c == '_')
            {
                int start = i;
                while (i + 1 < expression.Length && (Char.IsLetterOrDigit(expression[i + 1]) || expression[i + 1] == '_'))
                    i++;
                tokens.Add(new Token(TokenType.Identifier, expression[start..(i + 1)]));
                continue;
            }

            throw new InvalidOperationException($"Unsupported character '{c}' in preprocessor expression '{expression}'.");
        }

        return tokens;
    }

    private enum TokenType
    {
        Identifier,
        Not,
        And,
        Or,
        OpenParen,
        CloseParen
    }

    private readonly record struct Token(TokenType Type, string Value);
}

internal sealed class InternalizationRewriter(BuildOptions options, BuildReport report) : CSharpSyntaxRewriter
{
    internal const string SourceRootNamespace = "FastCloner";

    public override SyntaxNode? VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
    {
        NameSyntax rewrittenName = RewriteNamespaceName(node.Name);
        return base.VisitNamespaceDeclaration(node.WithName(rewrittenName));
    }

    public override SyntaxNode? VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
    {
        NameSyntax rewrittenName = RewriteNamespaceName(node.Name);
        return base.VisitFileScopedNamespaceDeclaration(node.WithName(rewrittenName));
    }

    public override SyntaxNode? VisitUsingDirective(UsingDirectiveSyntax node)
    {
        if (node.Name is null)
            return base.VisitUsingDirective(node);

        NameSyntax rewrittenName = RewriteNamespaceName(node.Name);
        return base.VisitUsingDirective(node.WithName(rewrittenName));
    }

    public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        ClassDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitClassDeclaration(updated);
    }

    public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
    {
        StructDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitStructDeclaration(updated);
    }

    public override SyntaxNode? VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
    {
        InterfaceDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitInterfaceDeclaration(updated);
    }

    public override SyntaxNode? VisitEnumDeclaration(EnumDeclarationSyntax node)
    {
        EnumDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitEnumDeclaration(updated);
    }

    public override SyntaxNode? VisitRecordDeclaration(RecordDeclarationSyntax node)
    {
        RecordDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitRecordDeclaration(updated);
    }

    public override SyntaxNode? VisitDelegateDeclaration(DelegateDeclarationSyntax node)
    {
        if (!IsTopLevel(node) || options.Visibility == VisibilityMode.Public || ShouldRemainPublic(node.Identifier.Text))
            return base.VisitDelegateDeclaration(node);

        if (!node.Modifiers.Any(SyntaxKind.PublicKeyword))
            return base.VisitDelegateDeclaration(node);

        SyntaxTokenList modifiers = ReplacePublicWithInternal(node.Modifiers);
        report.VisibilityRewrites++;
        return base.VisitDelegateDeclaration(node.WithModifiers(modifiers));
    }

    private T RewriteVisibility<T>(T node, string typeName) where T : BaseTypeDeclarationSyntax
    {
        if (!IsTopLevel(node) || options.Visibility == VisibilityMode.Public || ShouldRemainPublic(typeName))
            return node;
        if (!node.Modifiers.Any(SyntaxKind.PublicKeyword))
            return node;

        report.VisibilityRewrites++;
        return (T)node.WithModifiers(ReplacePublicWithInternal(node.Modifiers));
    }

    private static SyntaxTokenList ReplacePublicWithInternal(SyntaxTokenList modifiers)
    {
        List<SyntaxToken> updated = [];
        foreach (SyntaxToken token in modifiers)
        {
            if (token.IsKind(SyntaxKind.PublicKeyword))
                updated.Add(SyntaxFactory.Token(token.LeadingTrivia, SyntaxKind.InternalKeyword, token.TrailingTrivia));
            else
                updated.Add(token);
        }

        return SyntaxFactory.TokenList(updated);
    }

    private bool ShouldRemainPublic(string typeName)
    {
        if (options.PublicApi == PublicApiMode.All)
            return true;

        return options.PublicApi switch
        {
            PublicApiMode.None => false,
            PublicApiMode.FastCloner => typeName.Equals("FastCloner", StringComparison.Ordinal),
            PublicApiMode.Extensions => typeName.Equals("FastClonerExtensions", StringComparison.Ordinal),
            PublicApiMode.Behaviors => typeName.Equals("CloneBehavior", StringComparison.Ordinal) ||
                                       typeName.Contains("FastCloner", StringComparison.Ordinal) && typeName.EndsWith("Attribute", StringComparison.Ordinal),
            _ => false
        };
    }

    private bool IsTopLevel(SyntaxNode node)
    {
        return node.Parent is NamespaceDeclarationSyntax or FileScopedNamespaceDeclarationSyntax or CompilationUnitSyntax;
    }

    private NameSyntax RewriteNamespaceName(NameSyntax originalName)
    {
        string source = originalName.ToString();
        string rewritten = source switch
        {
            SourceRootNamespace => options.RootNamespace,
            _ when source.StartsWith(SourceRootNamespace + ".", StringComparison.Ordinal) => options.RootNamespace + source[SourceRootNamespace.Length..],
            _ => source
        };

        if (!String.Equals(source, rewritten, StringComparison.Ordinal))
            report.NamespaceRewrites++;

        return SyntaxFactory.ParseName(rewritten);
    }
}

internal sealed class MetadataTypeQualificationCollector(
    SemanticModel semanticModel,
    IAssemblySymbol generatedAssembly,
    HashSet<string> fullyQualifiedMetadataPrefixes) : CSharpSyntaxWalker
{
    private static readonly SymbolDisplayFormat FullyQualifiedTypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                              SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private readonly Dictionary<TextSpan, string> edits = new();

    public IReadOnlyDictionary<TextSpan, string> Edits => edits;

    public override void VisitIdentifierName(IdentifierNameSyntax node)
    {
        if (!TryCollectEdit(node))
            base.VisitIdentifierName(node);
    }

    public override void VisitGenericName(GenericNameSyntax node)
    {
        if (!TryCollectEdit(node))
            base.VisitGenericName(node);
    }

    public override void VisitQualifiedName(QualifiedNameSyntax node)
    {
        if (!TryCollectEdit(node))
            base.VisitQualifiedName(node);
    }

    public override void VisitAliasQualifiedName(AliasQualifiedNameSyntax node)
    {
        if (!TryCollectEdit(node))
            base.VisitAliasQualifiedName(node);
    }

    private bool TryCollectEdit(NameSyntax node)
    {
        if (!ShouldConsider(node))
            return false;

        ITypeSymbol? typeSymbol = ResolveTypeSymbol(node);
        if (!ShouldQualify(typeSymbol))
            return false;

        string fullyQualifiedName = typeSymbol!.ToDisplayString(FullyQualifiedTypeFormat);
        if (String.Equals(fullyQualifiedName, node.ToString(), StringComparison.Ordinal))
            return false;

        edits.TryAdd(node.Span, fullyQualifiedName);
        return true;
    }

    private ITypeSymbol? ResolveTypeSymbol(NameSyntax node)
    {
        if (node.Parent is AttributeSyntax attribute && attribute.Name == node)
            return semanticModel.GetTypeInfo(attribute).Type;

        if (IsDirectTypeContext(node))
        {
            ITypeSymbol? typeFromInfo = semanticModel.GetTypeInfo(node).Type;
            if (typeFromInfo is not null)
                return typeFromInfo;
        }

        SymbolInfo symbolInfo = semanticModel.GetSymbolInfo(node);
        ISymbol? symbol = symbolInfo.Symbol ?? symbolInfo.CandidateSymbols.FirstOrDefault();
        if (symbol is IAliasSymbol alias)
            symbol = alias.Target;

        return symbol switch
        {
            ITypeSymbol typeSymbol => typeSymbol,
            IMethodSymbol { MethodKind: MethodKind.Constructor } ctor => ctor.ContainingType,
            _ => null
        };
    }

    private bool ShouldQualify(ITypeSymbol? typeSymbol)
    {
        if (typeSymbol is null)
            return false;
        if (typeSymbol.TypeKind is TypeKind.Error or TypeKind.TypeParameter)
            return false;
        if (typeSymbol.SpecialType != SpecialType.None || typeSymbol.TypeKind == TypeKind.Dynamic)
            return false;

        return BuildOptions.ShouldFullyQualifyMetadataType(typeSymbol, generatedAssembly, fullyQualifiedMetadataPrefixes);
    }

    private static bool ShouldConsider(NameSyntax node)
    {
        if (node.Parent is NameSyntax)
            return false;
        if (node is AliasQualifiedNameSyntax { Alias.Identifier.ValueText: "global" })
            return false;
        if (node.Parent is MemberAccessExpressionSyntax memberAccess && memberAccess.Name == node)
            return false;
        if (node.Parent is MemberBindingExpressionSyntax memberBinding && memberBinding.Name == node)
            return false;

        return node.Parent is not (
            UsingDirectiveSyntax or
            NamespaceDeclarationSyntax or
            FileScopedNamespaceDeclarationSyntax or
            ExternAliasDirectiveSyntax or
            NameEqualsSyntax or
            NameColonSyntax or
            QualifiedCrefSyntax or
            XmlCrefAttributeSyntax);
    }

    private static bool IsDirectTypeContext(NameSyntax node)
    {
        return node.Parent switch
        {
            AttributeSyntax { Name: var name } => name == node,
            VariableDeclarationSyntax { Type: var type } => type == node,
            ParameterSyntax { Type: var type } => type == node,
            PropertyDeclarationSyntax { Type: var type } => type == node,
            EventDeclarationSyntax { Type: var type } => type == node,
            MethodDeclarationSyntax { ReturnType: var type } => type == node,
            LocalFunctionStatementSyntax { ReturnType: var type } => type == node,
            DelegateDeclarationSyntax { ReturnType: var type } => type == node,
            ObjectCreationExpressionSyntax { Type: var type } => type == node,
            CastExpressionSyntax { Type: var type } => type == node,
            TypeOfExpressionSyntax { Type: var type } => type == node,
            DefaultExpressionSyntax { Type: var type } => type == node,
            SizeOfExpressionSyntax { Type: var type } => type == node,
            ArrayTypeSyntax { ElementType: var type } => type == node,
            NullableTypeSyntax { ElementType: var type } => type == node,
            BaseTypeSyntax { Type: var type } => type == node,
            TupleElementSyntax { Type: var type } => type == node,
            TypeArgumentListSyntax => true,
            TypeConstraintSyntax => true,
            _ => false
        };
    }
}

internal static class SelfCheckCompiler
{
    public static int Check(
        IReadOnlyDictionary<string, string> sources,
        HashSet<string> symbols,
        HashSet<string> implicitUsings,
        string rootNamespace,
        HashSet<string> fullyQualifiedMetadataPrefixes)
    {
        CSharpParseOptions parseOptions = new(languageVersion: LanguageVersion.Preview, preprocessorSymbols: symbols);
        List<SyntaxTree> trees = [];
        if (implicitUsings.Count > 0)
        {
            StringBuilder implicitUsingsBuilder = new();
            foreach (string ns in implicitUsings.OrderBy(x => x, StringComparer.Ordinal))
                implicitUsingsBuilder.AppendLine($"global using {ns};");
            trees.Add(CSharpSyntaxTree.ParseText(implicitUsingsBuilder.ToString(), parseOptions, "__implicit_usings.g.cs"));
        }

        foreach ((string path, string content) in sources)
            trees.Add(CSharpSyntaxTree.ParseText(content, parseOptions, path));

        List<MetadataReference> references = [];
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (!String.IsNullOrWhiteSpace(tpa))
        {
            foreach (string assemblyPath in tpa.Split(Path.PathSeparator))
                references.Add(MetadataReference.CreateFromFile(assemblyPath));
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "FastCloner.Internalized.Check",
            trees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        int errors = ReportErrors(compilation.GetDiagnostics());
        if (errors > 0)
            return errors;
        if (fullyQualifiedMetadataPrefixes.Count == 0)
            return 0;

        Dictionary<string, string> sourceTexts = sources.ToDictionary(static kv => kv.Key, static kv => kv.Value, StringComparer.Ordinal);
        HashSet<string> unqualifiedMetadataTypeNames = FindUnqualifiedMetadataTypeNames(sourceTexts, implicitUsings, fullyQualifiedMetadataPrefixes);
        if (unqualifiedMetadataTypeNames.Count == 0)
            return 0;

        List<SyntaxTree> collisionTrees = CreateCollisionProbeTrees(rootNamespace, parseOptions, unqualifiedMetadataTypeNames);
        CSharpCompilation collisionCompilation = compilation.AddSyntaxTrees(collisionTrees);
        return ReportErrors(collisionCompilation.GetDiagnostics());
    }

    private static int ReportErrors(ImmutableArray<Diagnostic> diagnostics)
    {
        int errors = diagnostics.Count(d => d.Severity == DiagnosticSeverity.Error);
        foreach (Diagnostic diagnostic in diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error))
            Console.Error.WriteLine(diagnostic.ToString());

        return errors;
    }

    private static HashSet<string> FindUnqualifiedMetadataTypeNames(
        IReadOnlyDictionary<string, string> sourceTexts,
        HashSet<string> implicitUsings,
        HashSet<string> fullyQualifiedMetadataPrefixes)
    {
        HashSet<string> names = new(StringComparer.Ordinal);

        List<HashSet<string>> passSymbols = PreprocessorPruner.CollectBranchActivationSymbolSets(sourceTexts.Values);

        foreach (HashSet<string> symbols in passSymbols)
        {
            CSharpParseOptions passParseOptions = new(languageVersion: LanguageVersion.Preview, preprocessorSymbols: symbols);
            CSharpCompilation compilation = CreateCompilation(sourceTexts, passParseOptions, implicitUsings, out Dictionary<string, SyntaxTree> treeLookup);

            foreach (SyntaxTree tree in treeLookup.Values)
            {
                SemanticModel semanticModel = compilation.GetSemanticModel(tree);
                foreach (NameSyntax node in tree.GetRoot().DescendantNodes().OfType<NameSyntax>())
                {
                    if (!ShouldCheckCollision(node))
                        continue;

                    ITypeSymbol? typeSymbol = ResolveTypeSymbol(semanticModel, node);
                    if (!ShouldQualify(typeSymbol, compilation.Assembly, fullyQualifiedMetadataPrefixes))
                        continue;

                    if (!SyntaxFacts.IsValidIdentifier(typeSymbol!.Name))
                        continue;

                    names.Add(typeSymbol.Name);
                }
            }
        }

        return names;
    }

    private static CSharpCompilation CreateCompilation(
        IReadOnlyDictionary<string, string> sourceTexts,
        CSharpParseOptions parseOptions,
        HashSet<string> implicitUsings,
        out Dictionary<string, SyntaxTree> treeLookup)
    {
        treeLookup = new Dictionary<string, SyntaxTree>(StringComparer.Ordinal);
        List<SyntaxTree> trees = [];

        if (implicitUsings.Count > 0)
        {
            StringBuilder implicitUsingsBuilder = new();
            foreach (string ns in implicitUsings.OrderBy(x => x, StringComparer.Ordinal))
                implicitUsingsBuilder.AppendLine($"global using {ns};");
            trees.Add(CSharpSyntaxTree.ParseText(implicitUsingsBuilder.ToString(), parseOptions, "__implicit_usings.g.cs"));
        }

        foreach ((string path, string content) in sourceTexts)
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(content, parseOptions, path);
            trees.Add(tree);
            treeLookup[path] = tree;
        }

        return CSharpCompilation.Create(
            "FastCloner.Internalized.Check",
            trees,
            CreateMetadataReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static List<MetadataReference> CreateMetadataReferences()
    {
        List<MetadataReference> references = [];
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (!String.IsNullOrWhiteSpace(tpa))
        {
            foreach (string assemblyPath in tpa.Split(Path.PathSeparator))
                references.Add(MetadataReference.CreateFromFile(assemblyPath));
        }

        return references;
    }

    private static List<SyntaxTree> CreateCollisionProbeTrees(string rootNamespace, CSharpParseOptions parseOptions, HashSet<string> names)
    {
        List<SyntaxTree> trees = [];
        string[] prefixes = GetNamespacePrefixes(rootNamespace);
        int index = 0;

        foreach (string prefix in prefixes)
        {
            foreach (string name in names.OrderBy(x => x, StringComparer.Ordinal))
            {
                string source = $$"""
namespace {{prefix}}
{
    namespace {{name}}
    {
    }
}
""";
                trees.Add(CSharpSyntaxTree.ParseText(source, parseOptions, $"__collision_probe_{index++}.g.cs"));
            }
        }

        return trees;
    }

    private static string[] GetNamespacePrefixes(string rootNamespace)
    {
        string[] parts = rootNamespace.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        List<string> prefixes = new(parts.Length);
        for (int i = 0; i < parts.Length; i++)
            prefixes.Add(String.Join(".", parts.Take(i + 1)));

        return prefixes.ToArray();
    }

    private static ITypeSymbol? ResolveTypeSymbol(SemanticModel semanticModel, NameSyntax node)
    {
        if (node.Parent is AttributeSyntax attribute && attribute.Name == node)
            return semanticModel.GetTypeInfo(attribute).Type;

        if (IsDirectTypeContext(node))
        {
            ITypeSymbol? typeFromInfo = semanticModel.GetTypeInfo(node).Type;
            if (typeFromInfo is not null)
                return typeFromInfo;
        }

        SymbolInfo symbolInfo = semanticModel.GetSymbolInfo(node);
        ISymbol? symbol = symbolInfo.Symbol ?? symbolInfo.CandidateSymbols.FirstOrDefault();
        if (symbol is IAliasSymbol alias)
            symbol = alias.Target;

        return symbol switch
        {
            ITypeSymbol typeSymbol => typeSymbol,
            IMethodSymbol { MethodKind: MethodKind.Constructor } ctor => ctor.ContainingType,
            _ => null
        };
    }

    private static bool ShouldQualify(
        ITypeSymbol? typeSymbol,
        IAssemblySymbol generatedAssembly,
        HashSet<string> fullyQualifiedMetadataPrefixes)
    {
        if (typeSymbol is null)
            return false;
        if (typeSymbol.TypeKind is TypeKind.Error or TypeKind.TypeParameter)
            return false;
        if (typeSymbol.SpecialType != SpecialType.None || typeSymbol.TypeKind == TypeKind.Dynamic)
            return false;

        return BuildOptions.ShouldFullyQualifyMetadataType(typeSymbol, generatedAssembly, fullyQualifiedMetadataPrefixes);
    }

    private static bool ShouldCheckCollision(NameSyntax node)
    {
        if (node is not IdentifierNameSyntax and not GenericNameSyntax)
            return false;
        if (node.Parent is NameSyntax)
            return false;
        if (node.Parent is MemberAccessExpressionSyntax memberAccess && memberAccess.Name == node)
            return false;
        if (node.Parent is MemberBindingExpressionSyntax memberBinding && memberBinding.Name == node)
            return false;

        return node.Parent is not (
            UsingDirectiveSyntax or
            NamespaceDeclarationSyntax or
            FileScopedNamespaceDeclarationSyntax or
            ExternAliasDirectiveSyntax or
            NameEqualsSyntax or
            NameColonSyntax or
            QualifiedCrefSyntax or
            XmlCrefAttributeSyntax);
    }

    private static bool IsDirectTypeContext(NameSyntax node)
    {
        return node.Parent switch
        {
            AttributeSyntax { Name: var name } => name == node,
            VariableDeclarationSyntax { Type: var type } => type == node,
            ParameterSyntax { Type: var type } => type == node,
            PropertyDeclarationSyntax { Type: var type } => type == node,
            EventDeclarationSyntax { Type: var type } => type == node,
            MethodDeclarationSyntax { ReturnType: var type } => type == node,
            LocalFunctionStatementSyntax { ReturnType: var type } => type == node,
            DelegateDeclarationSyntax { ReturnType: var type } => type == node,
            ObjectCreationExpressionSyntax { Type: var type } => type == node,
            CastExpressionSyntax { Type: var type } => type == node,
            TypeOfExpressionSyntax { Type: var type } => type == node,
            DefaultExpressionSyntax { Type: var type } => type == node,
            SizeOfExpressionSyntax { Type: var type } => type == node,
            ArrayTypeSyntax { ElementType: var type } => type == node,
            NullableTypeSyntax { ElementType: var type } => type == node,
            BaseTypeSyntax { Type: var type } => type == node,
            TupleElementSyntax { Type: var type } => type == node,
            TypeArgumentListSyntax => true,
            TypeConstraintSyntax => true,
            _ => false
        };
    }
}
