using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FastCloner.Internalization.Builder;

internal static class Program
{
    private const string DefaultAttributionHeader = """
/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/
""";

    private static int Main(string[] args)
    {
        try
        {
            BuildOptions? options = BuildOptions.Parse(args);
            if (options is null)
            {
                PrintUsage();
                return 1;
            }

            BuildReport report = BuildInternalizedSources(options);
            report.Print();

            return report.HasErrors ? 1 : 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("Build failed.");
            Console.Error.WriteLine(ex);
            return 2;
        }
    }

    private static BuildReport BuildInternalizedSources(BuildOptions options)
    {
        if (!Directory.Exists(options.InputRoot))
            throw new DirectoryNotFoundException($"Input root not found: {options.InputRoot}");

        string[] files = RuntimeManifest.DiscoverRuntimeFiles(options.InputRoot, options.RuntimeOnly);
        BuildReport report = new(options, files.Length);
        HashSet<string> symbols = options.GetPreprocessorSymbols();
        CSharpParseOptions parseOptions = new(languageVersion: LanguageVersion.Preview);

        // Pass 1: transform all files, collect the union of all usings across every source file.
        Dictionary<string, CompilationUnitSyntax> transformed = new(StringComparer.Ordinal);
        HashSet<string> allUsings = new(StringComparer.Ordinal);

        foreach (string file in files)
        {
            string relativePath = Path.GetRelativePath(options.InputRoot, file).Replace('\\', '/');
            string source = File.ReadAllText(file);

            PruneResult prune = PreprocessorPruner.Transform(source, options.Preprocessor);
            source = prune.Text;
            report.PrunedDirectiveLines += prune.PrunedDirectiveLines;
            report.PrunedBranchLines += prune.PrunedBranchLines;

            SyntaxTree tree = CSharpSyntaxTree.ParseText(source, parseOptions);
            CompilationUnitSyntax root = tree.GetCompilationUnitRoot();

            foreach (UsingDirectiveSyntax u in root.Usings)
            {
                if (u.Alias is not null || u.StaticKeyword != default)
                    continue;
                string? name = u.Name?.ToString();
                if (!String.IsNullOrWhiteSpace(name))
                    allUsings.Add(name.StartsWith("global::", StringComparison.Ordinal) ? name["global::".Length..] : name);
            }

            var rewriter = new InternalizationRewriter(options, report);
            CompilationUnitSyntax rewrittenRoot = (CompilationUnitSyntax)rewriter.Visit(root)!;
            transformed[relativePath] = rewrittenRoot;
        }

        // Source project uses <ImplicitUsings>enable</ImplicitUsings>, so its files don't declare
        // the SDK-default usings explicitly. Discover them from the source csproj.
        foreach (string ns in DiscoverSourceImplicitUsings(options.InputRoot))
            allUsings.Add(ns);

        // Remove the source project's own namespaces — they've been rewritten to the target namespace
        // and would cause unresolvable CS0234 errors that cascade through the semantic model.
        allUsings.RemoveWhere(static ns => ns.Equals(InternalizationRewriter.SourceRootNamespace, StringComparison.Ordinal) ||
                                           ns.StartsWith(InternalizationRewriter.SourceRootNamespace + ".", StringComparison.Ordinal));

        // Inject the full union of usings into every file so the compilation resolves all symbols.
        foreach (string path in transformed.Keys.ToList())
            transformed[path] = AddAllCandidateUsings(transformed[path], allUsings, options.ImplicitUsings);

        // Pass 2: compile all files together, ask the compiler which usings are unnecessary (CS8019).
        Dictionary<string, HashSet<int>> unnecessaryUsingSpans = FindUnnecessaryUsings(transformed, parseOptions, options.ImplicitUsings);

        // Pass 3: strip compiler-flagged usings + implicit usings, normalize, apply global:: rewrites, add header.
        Dictionary<string, string> generated = new(StringComparer.Ordinal);
        foreach ((string relativePath, CompilationUnitSyntax unit) in transformed)
        {
            HashSet<int> unnecessarySpanStarts = unnecessaryUsingSpans.GetValueOrDefault(relativePath) ?? [];
            CompilationUnitSyntax trimmed = StripUnnecessaryUsings(unit, unnecessarySpanStarts, options.ImplicitUsings);
            string rewritten = trimmed.NormalizeWhitespace(eol: "\n").ToFullString() + "\n";
            rewritten = rewritten.Replace("global::FastCloner.", $"global::{options.RootNamespace}.", StringComparison.Ordinal);
            rewritten = rewritten.Replace("global::FastCloner", $"global::{options.RootNamespace}", StringComparison.Ordinal);
            rewritten = AddGeneratedHeader(rewritten, options);
            generated[relativePath] = rewritten;
        }

        if (options.DryRun)
        {
            foreach (string path in generated.Keys.OrderBy(x => x, StringComparer.Ordinal))
                Console.WriteLine($"[dry-run] {path}");
            if (!options.NoLicense)
            {
                string? sourceLicense = GetSourceLicensePath(options.InputRoot);
                if (!String.IsNullOrWhiteSpace(sourceLicense))
                    Console.WriteLine($"[dry-run] LICENSE <= {sourceLicense}");
            }
        }
        else
        {
            Directory.CreateDirectory(options.Output);

            foreach ((string relativePath, string contents) in generated.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                string outPath = Path.Combine(options.Output, relativePath.Replace('/', Path.DirectorySeparatorChar));
                string? outDir = Path.GetDirectoryName(outPath);
                if (!String.IsNullOrEmpty(outDir))
                    Directory.CreateDirectory(outDir);

                File.WriteAllText(outPath, contents, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
                report.WrittenFiles++;
            }

            if (!options.NoLicense)
            {
                string? sourceLicense = GetSourceLicensePath(options.InputRoot);
                if (!String.IsNullOrWhiteSpace(sourceLicense))
                {
                    string targetLicense = Path.Combine(options.Output, "LICENSE");
                    File.Copy(sourceLicense, targetLicense, overwrite: true);
                    report.CopiedLicense = true;
                }
            }
        }

        if (options.SelfCheck)
            report.CompilationErrors = SelfCheckCompiler.Check(generated, symbols, options.ImplicitUsings);

        return report;
    }

    private static string? GetSourceLicensePath(string inputRoot)
    {
        string rootCandidate = Path.GetFullPath(Path.Combine(inputRoot, "..", "..", "LICENSE"));
        if (File.Exists(rootCandidate))
            return rootCandidate;

        string localCandidate = Path.GetFullPath(Path.Combine(inputRoot, "LICENSE"));
        if (File.Exists(localCandidate))
            return localCandidate;

        return null;
    }

    private static string AddGeneratedHeader(string source, BuildOptions options)
    {
        string? customHeader = NormalizeHeader(options.CustomHeader);
        bool includeDefaultAttribution = !options.NoAttribution;

        if (!includeDefaultAttribution && String.IsNullOrWhiteSpace(customHeader))
            return source;

        StringBuilder sb = new();
        if (includeDefaultAttribution)
        {
            sb.Append(DefaultAttributionHeader.TrimEnd());
            sb.Append('\n');
        }

        if (!String.IsNullOrWhiteSpace(customHeader))
        {
            sb.Append(customHeader.TrimEnd());
            sb.Append('\n');
        }

        sb.Append('\n');
        sb.Append(source);
        return sb.ToString();
    }

    private static string? NormalizeHeader(string? header)
    {
        if (String.IsNullOrWhiteSpace(header))
            return null;

        return header
            .Replace("\\r\\n", "\n", StringComparison.Ordinal)
            .Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\\r", "\n", StringComparison.Ordinal);
    }

    private static CompilationUnitSyntax AddAllCandidateUsings(CompilationUnitSyntax unit, HashSet<string> candidateUsings, HashSet<string> implicitUsings)
    {
        HashSet<string> existing = new(unit.Usings
            .Where(u => u.Alias is null && u.StaticKeyword == default)
            .Select(u => u.Name?.ToString() ?? String.Empty)
            .Where(n => !String.IsNullOrWhiteSpace(n))
            .Select(n => n.StartsWith("global::", StringComparison.Ordinal) ? n["global::".Length..] : n),
            StringComparer.Ordinal);

        List<UsingDirectiveSyntax> additions = candidateUsings
            .Where(ns => !implicitUsings.Contains(ns) && !existing.Contains(ns))
            .OrderBy(ns => ns, StringComparer.Ordinal)
            .Select(ns => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(ns)))
            .ToList();

        return additions.Count == 0 ? unit : unit.WithUsings(unit.Usings.AddRange(additions));
    }

    private static Dictionary<string, HashSet<int>> FindUnnecessaryUsings(
        Dictionary<string, CompilationUnitSyntax> allFiles,
        CSharpParseOptions parseOptions,
        HashSet<string> implicitUsings)
    {
        List<MetadataReference> references = [];
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (!String.IsNullOrWhiteSpace(tpa))
        {
            foreach (string assemblyPath in tpa.Split(Path.PathSeparator))
                references.Add(MetadataReference.CreateFromFile(assemblyPath));
        }

        Dictionary<string, SyntaxTree> treeLookup = new(StringComparer.Ordinal);
        List<SyntaxTree> trees = [];

        if (implicitUsings.Count > 0)
        {
            StringBuilder implicitSb = new();
            foreach (string ns in implicitUsings.OrderBy(x => x, StringComparer.Ordinal))
                implicitSb.AppendLine($"global using {ns};");
            trees.Add(CSharpSyntaxTree.ParseText(implicitSb.ToString(), parseOptions, "__implicit_usings.g.cs"));
        }

        foreach ((string path, CompilationUnitSyntax unit) in allFiles)
        {
            SyntaxTree tree = CSharpSyntaxTree.Create(unit, parseOptions, path, Encoding.UTF8);
            trees.Add(tree);
            treeLookup[path] = tree;
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "__using_resolution",
            trees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithSpecificDiagnosticOptions(new Dictionary<string, ReportDiagnostic>
                {
                    ["CS8019"] = ReportDiagnostic.Warn
                }));

        Dictionary<string, HashSet<int>> result = new(StringComparer.Ordinal);
        ImmutableArray<Diagnostic> diagnostics = compilation.GetDiagnostics();

        foreach (Diagnostic diag in diagnostics)
        {
            if (diag.Id != "CS8019")
                continue;

            string filePath = diag.Location.SourceTree?.FilePath ?? String.Empty;
            if (String.IsNullOrEmpty(filePath) || !treeLookup.ContainsKey(filePath))
                continue;

            if (!result.TryGetValue(filePath, out HashSet<int>? spans))
            {
                spans = [];
                result[filePath] = spans;
            }

            spans.Add(diag.Location.SourceSpan.Start);
        }

        return result;
    }

    private static CompilationUnitSyntax StripUnnecessaryUsings(
        CompilationUnitSyntax unit,
        HashSet<int> unnecessarySpanStarts,
        HashSet<string> implicitUsings)
    {
        SyntaxList<UsingDirectiveSyntax> filtered = new(unit.Usings.Where(u =>
        {
            if (u.Alias is not null || u.StaticKeyword != default)
                return true;

            string? name = u.Name?.ToString();
            if (String.IsNullOrWhiteSpace(name))
                return true;

            string normalized = name.StartsWith("global::", StringComparison.Ordinal) ? name["global::".Length..] : name;

            if (implicitUsings.Contains(normalized))
                return false;

            return !unnecessarySpanStarts.Contains(u.SpanStart);
        }));

        return unit.WithUsings(filtered);
    }

    private static HashSet<string> DiscoverSourceImplicitUsings(string inputRoot)
    {
        HashSet<string> result = new(StringComparer.Ordinal);
        string? csproj = Directory.GetFiles(inputRoot, "*.csproj", SearchOption.TopDirectoryOnly).FirstOrDefault()
                         ?? Directory.GetFiles(Path.GetDirectoryName(inputRoot) ?? inputRoot, "*.csproj", SearchOption.TopDirectoryOnly).FirstOrDefault();

        bool hasImplicitUsings = false;
        if (csproj is not null)
        {
            string content = File.ReadAllText(csproj);
            hasImplicitUsings = content.Contains("<ImplicitUsings>enable</ImplicitUsings>", StringComparison.OrdinalIgnoreCase);
        }

        if (hasImplicitUsings)
        {
            result.Add("System");
            result.Add("System.Collections.Generic");
            result.Add("System.IO");
            result.Add("System.Linq");
            result.Add("System.Net.Http");
            result.Add("System.Threading");
            result.Add("System.Threading.Tasks");
        }

        return result;
    }

    private static void PrintUsage()
    {
        Console.WriteLine("""
Usage:
  FastCloner.Internalization.Builder --root-namespace <ns> --output <path> [options]

Required:
  --root-namespace <ns>                     Target root namespace for generated code.
  --output <path>                           Output directory for generated files.

Optional:
  --input-root <path>                       FastCloner runtime source root (defaults to ../FastCloner).
  --preprocessor <k=v;k2=v2>                Per-symbol preprocessor overrides.
                                            Example:
                                              MODERN=true;NET8_0_OR_GREATER=true
                                              MODERN=true;SOMETHING=random_text
                                            Special values:
                                              true / false (recognized booleans)
                                            Non-boolean values are used as direct token replacement in #if expressions.
  --implicit-usings <ns1;ns2;...>          List of namespaces assumed implicit in target project.
                                            When provided, matching global usings are omitted from generated code.
  --visibility <public|internal>            Top-level visibility rewrite mode (default: internal).
  --public-api <none|fastcloner|extensions|behaviors|all>
                                            Exceptions to keep public when visibility=internal (default: none).
  --runtime-only <true|false>               Include only runtime sources (default: true).
  --no-license                              Do not copy LICENSE file to output root.
  --no-attribution                          Do not emit default attribution header in generated .cs files.
  --header <text>                           Custom header/banner inserted under default attribution header.
  --dry-run                                 Print generation plan, do not write files.
  --self-check                              Compile generated tree and report compile errors.
""");
    }
}

internal enum VisibilityMode
{
    Public,
    Internal
}

internal enum PublicApiMode
{
    None,
    FastCloner,
    Extensions,
    Behaviors,
    All
}

internal sealed class BuildOptions
{
    public required string RootNamespace { get; init; }
    public required string Output { get; init; }
    public required string InputRoot { get; init; }
    public required Dictionary<string, string> Preprocessor { get; init; }
    public required HashSet<string> ImplicitUsings { get; init; }
    public required VisibilityMode Visibility { get; init; }
    public required PublicApiMode PublicApi { get; init; }
    public required bool RuntimeOnly { get; init; }
    public required bool NoLicense { get; init; }
    public required bool NoAttribution { get; init; }
    public required string? CustomHeader { get; init; }
    public required bool DryRun { get; init; }
    public required bool SelfCheck { get; init; }

    public static BuildOptions? Parse(string[] args)
    {
        Dictionary<string, string?> kv = ParseArgs(args);
        if (kv.Count == 0 || kv.ContainsKey("--help") || kv.ContainsKey("-h"))
            return null;

        if (!kv.TryGetValue("--root-namespace", out string? rootNs) || String.IsNullOrWhiteSpace(rootNs))
            throw new ArgumentException("--root-namespace is required.");
        if (!kv.TryGetValue("--output", out string? output) || String.IsNullOrWhiteSpace(output))
            throw new ArgumentException("--output is required.");

        string defaultInputRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "FastCloner"));
        string inputRoot = Get(kv, "--input-root", defaultInputRoot);
        Dictionary<string, string> preprocessor = ParsePreprocessor(Get(kv, "--preprocessor", String.Empty));
        HashSet<string> implicitUsings = ParseNamespaceList(Get(kv, "--implicit-usings", String.Empty));

        VisibilityMode visibility = ParseEnum(Get(kv, "--visibility", "internal"), new Dictionary<string, VisibilityMode>(StringComparer.OrdinalIgnoreCase)
        {
            ["public"] = VisibilityMode.Public,
            ["internal"] = VisibilityMode.Internal
        }, "--visibility");

        PublicApiMode publicApi = ParseEnum(Get(kv, "--public-api", "none"), new Dictionary<string, PublicApiMode>(StringComparer.OrdinalIgnoreCase)
        {
            ["none"] = PublicApiMode.None,
            ["fastcloner"] = PublicApiMode.FastCloner,
            ["extensions"] = PublicApiMode.Extensions,
            ["behaviors"] = PublicApiMode.Behaviors,
            ["all"] = PublicApiMode.All
        }, "--public-api");

        bool runtimeOnly = ParseBool(Get(kv, "--runtime-only", "true"), "--runtime-only");
        bool noLicense = kv.ContainsKey("--no-license");
        bool noAttribution = kv.ContainsKey("--no-attribution");
        string? customHeader = kv.TryGetValue("--header", out string? headerValue) && !String.IsNullOrWhiteSpace(headerValue)
            ? headerValue
            : null;
        bool dryRun = kv.ContainsKey("--dry-run");
        bool selfCheck = kv.ContainsKey("--self-check");

        return new BuildOptions
        {
            RootNamespace = rootNs.Trim(),
            Output = Path.GetFullPath(output),
            InputRoot = Path.GetFullPath(inputRoot),
            Preprocessor = preprocessor,
            ImplicitUsings = implicitUsings,
            Visibility = visibility,
            PublicApi = publicApi,
            RuntimeOnly = runtimeOnly,
            NoLicense = noLicense,
            NoAttribution = noAttribution,
            CustomHeader = customHeader,
            DryRun = dryRun,
            SelfCheck = selfCheck
        };
    }

    public HashSet<string> GetPreprocessorSymbols()
    {
        HashSet<string> symbols = new(StringComparer.Ordinal);
        foreach ((string key, string value) in Preprocessor)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "true"))
                symbols.Add(key);
        }

        return symbols;
    }

    private static Dictionary<string, string> ParsePreprocessor(string raw)
    {
        Dictionary<string, string> map = new(StringComparer.Ordinal);
        if (String.IsNullOrWhiteSpace(raw))
            return map;

        foreach (string pair in raw.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            int eq = pair.IndexOf('=');
            if (eq <= 0 || eq == pair.Length - 1)
                throw new ArgumentException($"Invalid --preprocessor entry '{pair}'. Expected KEY=VALUE.");

            string key = pair[..eq].Trim();
            string value = pair[(eq + 1)..].Trim();
            if (key.Length == 0 || value.Length == 0)
                throw new ArgumentException($"Invalid --preprocessor entry '{pair}'. Empty key/value.");

            map[key] = value;
        }

        return map;
    }

    private static HashSet<string> ParseNamespaceList(string raw)
    {
        HashSet<string> set = new(StringComparer.Ordinal);
        if (String.IsNullOrWhiteSpace(raw))
            return set;

        foreach (string value in raw.Split([';', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (value.Length == 0)
                continue;
            set.Add(value.StartsWith("global::", StringComparison.Ordinal) ? value["global::".Length..] : value);
        }

        return set;
    }

    private static Dictionary<string, string?> ParseArgs(string[] args)
    {
        Dictionary<string, string?> parsed = new(StringComparer.OrdinalIgnoreCase);
        for (int i = 0; i < args.Length; i++)
        {
            string current = args[i];
            if (!current.StartsWith('-'))
                continue;

            if (i + 1 < args.Length && !args[i + 1].StartsWith('-'))
            {
                parsed[current] = args[i + 1];
                i++;
            }
            else
            {
                parsed[current] = null;
            }
        }

        return parsed;
    }

    private static string Get(Dictionary<string, string?> args, string key, string defaultValue)
    {
        return args.TryGetValue(key, out string? value) && !String.IsNullOrWhiteSpace(value)
            ? value
            : defaultValue;
    }

    private static T ParseEnum<T>(string value, IReadOnlyDictionary<string, T> map, string optionName) where T : struct
    {
        if (map.TryGetValue(value, out T mode))
            return mode;

        throw new ArgumentException($"Invalid value '{value}' for {optionName}.");
    }

    private static bool ParseBool(string value, string optionName)
    {
        if (Boolean.TryParse(value, out bool parsed))
            return parsed;

        throw new ArgumentException($"Invalid boolean value '{value}' for {optionName}.");
    }
}

internal sealed class BuildReport(BuildOptions options, int discoveredFiles)
{
    public BuildOptions Options { get; } = options;
    public int DiscoveredFiles { get; } = discoveredFiles;
    public int WrittenFiles { get; set; }
    public int NamespaceRewrites { get; set; }
    public int VisibilityRewrites { get; set; }
    public int PrunedDirectiveLines { get; set; }
    public int PrunedBranchLines { get; set; }
    public bool CopiedLicense { get; set; }
    public int CompilationErrors { get; set; }
    public bool HasErrors => CompilationErrors > 0;

    public void Print()
    {
        Console.WriteLine("FastCloner internalization builder report");
        Console.WriteLine($"  input-root: {Options.InputRoot}");
        Console.WriteLine($"  output: {Options.Output}");
        Console.WriteLine($"  preprocessor: {(Options.Preprocessor.Count == 0 ? "(none)" : String.Join("; ", Options.Preprocessor.Select(kv => $"{kv.Key}={kv.Value}")))}");
        Console.WriteLine($"  implicit-usings: {(Options.ImplicitUsings.Count == 0 ? "(none)" : String.Join("; ", Options.ImplicitUsings.OrderBy(x => x, StringComparer.Ordinal)))}");
        Console.WriteLine($"  visibility: {Options.Visibility} (public-api: {Options.PublicApi})");
        Console.WriteLine($"  attribution header: {(!Options.NoAttribution ? "default" : "disabled")}");
        Console.WriteLine($"  custom header: {(String.IsNullOrWhiteSpace(Options.CustomHeader) ? "(none)" : "provided")}");
        Console.WriteLine($"  discovered files: {DiscoveredFiles}");
        Console.WriteLine($"  written files: {(Options.DryRun ? 0 : WrittenFiles)}");
        Console.WriteLine($"  namespace rewrites: {NamespaceRewrites}");
        Console.WriteLine($"  visibility rewrites: {VisibilityRewrites}");
        Console.WriteLine($"  pruned directive lines: {PrunedDirectiveLines}");
        Console.WriteLine($"  pruned branch lines: {PrunedBranchLines}");
        Console.WriteLine($"  copied license: {CopiedLicense}");
        if (Options.SelfCheck)
            Console.WriteLine($"  compile errors: {CompilationErrors}");
    }
}

internal static class RuntimeManifest
{
    public static string[] DiscoverRuntimeFiles(string inputRoot, bool runtimeOnly)
    {
        IEnumerable<string> files = Directory
            .GetFiles(inputRoot, "*.cs", SearchOption.AllDirectories)
            .Where(static path => !path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase))
            .Where(static path => !path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase));

        if (runtimeOnly)
        {
            files = files
                .Where(static path => !path.EndsWith("AssemblyInfo.cs", StringComparison.OrdinalIgnoreCase))
                .Where(path =>
                {
                    string relative = Path.GetRelativePath(inputRoot, path).Replace('\\', '/');
                    return relative.StartsWith("Code/", StringComparison.Ordinal) ||
                           relative.Equals("FastCloner.cs", StringComparison.OrdinalIgnoreCase);
                });
        }

        return files
            .OrderBy(path => Path.GetRelativePath(inputRoot, path), StringComparer.Ordinal)
            .ToArray();
    }
}

internal readonly record struct PruneResult(string Text, int PrunedDirectiveLines, int PrunedBranchLines);

internal static class PreprocessorPruner
{
    public static PruneResult Transform(string source, IReadOnlyDictionary<string, string> replacements)
    {
        string[] lines = source.Replace("\r\n", "\n").Split('\n');
        string[] rewrittenLines = new string[lines.Length];
        bool allResolvable = true;

        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            if (TryParseDirective(line.TrimStart(), out string directive, out string expression) &&
                (directive == "if" || directive == "elif"))
            {
                string replacedExpression = ReplaceSymbols(expression, replacements);
                if (TryEvaluateBoolExpression(replacedExpression, out _))
                {
                    rewrittenLines[i] = ReplaceDirectiveExpression(line, directive, replacedExpression);
                }
                else
                {
                    allResolvable = false;
                    rewrittenLines[i] = ReplaceDirectiveExpression(line, directive, replacedExpression);
                }
            }
            else
            {
                rewrittenLines[i] = line;
            }
        }

        if (!allResolvable)
            return new PruneResult(String.Join('\n', rewrittenLines), 0, 0);

        return PruneResolved(String.Join('\n', rewrittenLines));
    }

    private static PruneResult PruneResolved(string source)
    {
        string[] lines = source.Split('\n');
        List<string> output = new(lines.Length);
        Stack<ConditionalFrame> stack = new();
        bool active = true;
        int prunedDirectives = 0;
        int prunedBranchLines = 0;

        foreach (string line in lines)
        {
            string trimmed = line.TrimStart();
            if (!trimmed.StartsWith('#'))
            {
                if (active)
                    output.Add(line);
                else
                    prunedBranchLines++;
                continue;
            }

            if (!TryParseDirective(trimmed, out string directive, out string expression))
            {
                if (active)
                    output.Add(line);
                continue;
            }

            prunedDirectives++;

            switch (directive)
            {
                case "if":
                {
                    bool parentActive = active;
                    bool currentActive = parentActive && SymbolExpressionEvaluator.Evaluate(expression);
                    stack.Push(new ConditionalFrame(parentActive, currentActive, currentActive));
                    active = currentActive;
                    break;
                }
                case "elif":
                {
                    ConditionalFrame frame = stack.Pop();
                    bool currentActive = frame.ParentActive &&
                                         !frame.BranchTaken &&
                                         SymbolExpressionEvaluator.Evaluate(expression);
                    stack.Push(frame with { BranchTaken = frame.BranchTaken || currentActive, CurrentActive = currentActive });
                    active = currentActive;
                    break;
                }
                case "else":
                {
                    ConditionalFrame frame = stack.Pop();
                    bool currentActive = frame.ParentActive && !frame.BranchTaken;
                    stack.Push(frame with { BranchTaken = true, CurrentActive = currentActive });
                    active = currentActive;
                    break;
                }
                case "endif":
                {
                    _ = stack.Pop();
                    active = stack.Count == 0 || stack.Peek().CurrentActive;
                    break;
                }
            }
        }

        string prunedText = String.Join('\n', output);
        return new PruneResult(prunedText, prunedDirectives, prunedBranchLines);
    }

    private static bool TryEvaluateBoolExpression(string expression, out bool result)
    {
        try
        {
            result = SymbolExpressionEvaluator.Evaluate(expression);
            return true;
        }
        catch
        {
            result = false;
            return false;
        }
    }

    private static string ReplaceDirectiveExpression(string originalLine, string directive, string newExpression)
    {
        int hashIndex = originalLine.IndexOf('#');
        if (hashIndex < 0)
            return originalLine;

        string indentation = originalLine[..hashIndex];
        return $"{indentation}#{directive} {newExpression}";
    }

    private static string ReplaceSymbols(string expression, IReadOnlyDictionary<string, string> replacements)
    {
        StringBuilder sb = new(expression.Length);
        for (int i = 0; i < expression.Length; i++)
        {
            char c = expression[i];
            if (Char.IsLetterOrDigit(c) || c == '_')
            {
                int start = i;
                while (i + 1 < expression.Length && (Char.IsLetterOrDigit(expression[i + 1]) || expression[i + 1] == '_'))
                    i++;

                string symbol = expression[start..(i + 1)];
                if (replacements.TryGetValue(symbol, out string? replacement))
                    sb.Append(replacement);
                else
                    sb.Append(symbol);
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }

    private static bool TryParseDirective(string trimmedLine, out string directive, out string expression)
    {
        directive = String.Empty;
        expression = String.Empty;

        if (!trimmedLine.StartsWith('#'))
            return false;

        string body = trimmedLine[1..].Trim();
        if (body.StartsWith("if ", StringComparison.Ordinal))
        {
            directive = "if";
            expression = body[3..].Trim();
            return true;
        }
        if (body.StartsWith("elif ", StringComparison.Ordinal))
        {
            directive = "elif";
            expression = body[5..].Trim();
            return true;
        }
        if (body.Equals("else", StringComparison.Ordinal))
        {
            directive = "else";
            return true;
        }
        if (body.Equals("endif", StringComparison.Ordinal))
        {
            directive = "endif";
            return true;
        }

        return false;
    }

    private readonly record struct ConditionalFrame(bool ParentActive, bool BranchTaken, bool CurrentActive);
}

internal static class SymbolExpressionEvaluator
{
    public static bool Evaluate(string expression)
    {
        if (String.IsNullOrWhiteSpace(expression))
            return false;

        List<Token> tokens = Tokenize(expression);
        int index = 0;
        bool result = ParseOr(tokens, ref index);
        if (index != tokens.Count)
            throw new InvalidOperationException($"Unexpected token in preprocessor expression: '{tokens[index].Value}'.");
        return result;
    }

    private static bool ParseOr(List<Token> tokens, ref int index)
    {
        bool left = ParseAnd(tokens, ref index);
        while (Match(tokens, ref index, TokenType.Or))
            left = left || ParseAnd(tokens, ref index);
        return left;
    }

    private static bool ParseAnd(List<Token> tokens, ref int index)
    {
        bool left = ParseUnary(tokens, ref index);
        while (Match(tokens, ref index, TokenType.And))
            left = left && ParseUnary(tokens, ref index);
        return left;
    }

    private static bool ParseUnary(List<Token> tokens, ref int index)
    {
        if (Match(tokens, ref index, TokenType.Not))
            return !ParseUnary(tokens, ref index);
        return ParsePrimary(tokens, ref index);
    }

    private static bool ParsePrimary(List<Token> tokens, ref int index)
    {
        if (Match(tokens, ref index, TokenType.OpenParen))
        {
            bool value = ParseOr(tokens, ref index);
            Expect(tokens, ref index, TokenType.CloseParen);
            return value;
        }

        Token token = Expect(tokens, ref index, TokenType.Identifier);
        if (token.Value.Equals("true", StringComparison.OrdinalIgnoreCase))
            return true;
        if (token.Value.Equals("false", StringComparison.OrdinalIgnoreCase))
            return false;

        throw new InvalidOperationException($"Unresolved symbol '{token.Value}' in preprocessor expression.");
    }

    private static Token Expect(List<Token> tokens, ref int index, TokenType type)
    {
        if (index >= tokens.Count || tokens[index].Type != type)
            throw new InvalidOperationException($"Unexpected token while parsing preprocessor expression. Expected {type}.");

        return tokens[index++];
    }

    private static bool Match(List<Token> tokens, ref int index, TokenType type)
    {
        if (index < tokens.Count && tokens[index].Type == type)
        {
            index++;
            return true;
        }
        return false;
    }

    private static List<Token> Tokenize(string expression)
    {
        List<Token> tokens = [];
        for (int i = 0; i < expression.Length; i++)
        {
            char c = expression[i];
            if (Char.IsWhiteSpace(c))
                continue;

            if (c == '!' )
            {
                tokens.Add(new Token(TokenType.Not, "!"));
                continue;
            }
            if (c == '&' && i + 1 < expression.Length && expression[i + 1] == '&')
            {
                tokens.Add(new Token(TokenType.And, "&&"));
                i++;
                continue;
            }
            if (c == '|' && i + 1 < expression.Length && expression[i + 1] == '|')
            {
                tokens.Add(new Token(TokenType.Or, "||"));
                i++;
                continue;
            }
            if (c == '(')
            {
                tokens.Add(new Token(TokenType.OpenParen, "("));
                continue;
            }
            if (c == ')')
            {
                tokens.Add(new Token(TokenType.CloseParen, ")"));
                continue;
            }

            if (Char.IsLetterOrDigit(c) || c == '_')
            {
                int start = i;
                while (i + 1 < expression.Length && (Char.IsLetterOrDigit(expression[i + 1]) || expression[i + 1] == '_'))
                    i++;
                tokens.Add(new Token(TokenType.Identifier, expression[start..(i + 1)]));
                continue;
            }

            throw new InvalidOperationException($"Unsupported character '{c}' in preprocessor expression '{expression}'.");
        }

        return tokens;
    }

    private enum TokenType
    {
        Identifier,
        Not,
        And,
        Or,
        OpenParen,
        CloseParen
    }

    private readonly record struct Token(TokenType Type, string Value);
}

internal sealed class InternalizationRewriter(BuildOptions options, BuildReport report) : CSharpSyntaxRewriter
{
    internal const string SourceRootNamespace = "FastCloner";

    public override SyntaxNode? VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
    {
        NameSyntax rewrittenName = RewriteNamespaceName(node.Name);
        return base.VisitNamespaceDeclaration(node.WithName(rewrittenName));
    }

    public override SyntaxNode? VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
    {
        NameSyntax rewrittenName = RewriteNamespaceName(node.Name);
        return base.VisitFileScopedNamespaceDeclaration(node.WithName(rewrittenName));
    }

    public override SyntaxNode? VisitUsingDirective(UsingDirectiveSyntax node)
    {
        if (node.Name is null)
            return base.VisitUsingDirective(node);

        NameSyntax rewrittenName = RewriteNamespaceName(node.Name);
        return base.VisitUsingDirective(node.WithName(rewrittenName));
    }

    public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        ClassDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitClassDeclaration(updated);
    }

    public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
    {
        StructDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitStructDeclaration(updated);
    }

    public override SyntaxNode? VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
    {
        InterfaceDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitInterfaceDeclaration(updated);
    }

    public override SyntaxNode? VisitEnumDeclaration(EnumDeclarationSyntax node)
    {
        EnumDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitEnumDeclaration(updated);
    }

    public override SyntaxNode? VisitRecordDeclaration(RecordDeclarationSyntax node)
    {
        RecordDeclarationSyntax updated = RewriteVisibility(node, node.Identifier.Text);
        return base.VisitRecordDeclaration(updated);
    }

    public override SyntaxNode? VisitDelegateDeclaration(DelegateDeclarationSyntax node)
    {
        if (!IsTopLevel(node) || options.Visibility == VisibilityMode.Public || ShouldRemainPublic(node.Identifier.Text))
            return base.VisitDelegateDeclaration(node);

        if (!node.Modifiers.Any(SyntaxKind.PublicKeyword))
            return base.VisitDelegateDeclaration(node);

        SyntaxTokenList modifiers = ReplacePublicWithInternal(node.Modifiers);
        report.VisibilityRewrites++;
        return base.VisitDelegateDeclaration(node.WithModifiers(modifiers));
    }

    private T RewriteVisibility<T>(T node, string typeName) where T : BaseTypeDeclarationSyntax
    {
        if (!IsTopLevel(node) || options.Visibility == VisibilityMode.Public || ShouldRemainPublic(typeName))
            return node;
        if (!node.Modifiers.Any(SyntaxKind.PublicKeyword))
            return node;

        report.VisibilityRewrites++;
        return (T)node.WithModifiers(ReplacePublicWithInternal(node.Modifiers));
    }

    private static SyntaxTokenList ReplacePublicWithInternal(SyntaxTokenList modifiers)
    {
        List<SyntaxToken> updated = [];
        foreach (SyntaxToken token in modifiers)
        {
            if (token.IsKind(SyntaxKind.PublicKeyword))
                updated.Add(SyntaxFactory.Token(token.LeadingTrivia, SyntaxKind.InternalKeyword, token.TrailingTrivia));
            else
                updated.Add(token);
        }

        return SyntaxFactory.TokenList(updated);
    }

    private bool ShouldRemainPublic(string typeName)
    {
        if (options.PublicApi == PublicApiMode.All)
            return true;

        return options.PublicApi switch
        {
            PublicApiMode.None => false,
            PublicApiMode.FastCloner => typeName.Equals("FastCloner", StringComparison.Ordinal),
            PublicApiMode.Extensions => typeName.Equals("FastClonerExtensions", StringComparison.Ordinal),
            PublicApiMode.Behaviors => typeName.Equals("CloneBehavior", StringComparison.Ordinal) ||
                                       typeName.Contains("FastCloner", StringComparison.Ordinal) && typeName.EndsWith("Attribute", StringComparison.Ordinal),
            _ => false
        };
    }

    private bool IsTopLevel(SyntaxNode node)
    {
        return node.Parent is NamespaceDeclarationSyntax or FileScopedNamespaceDeclarationSyntax or CompilationUnitSyntax;
    }

    private NameSyntax RewriteNamespaceName(NameSyntax originalName)
    {
        string source = originalName.ToString();
        string rewritten = source switch
        {
            SourceRootNamespace => options.RootNamespace,
            _ when source.StartsWith(SourceRootNamespace + ".", StringComparison.Ordinal) => options.RootNamespace + source[SourceRootNamespace.Length..],
            _ => source
        };

        if (!String.Equals(source, rewritten, StringComparison.Ordinal))
            report.NamespaceRewrites++;

        return SyntaxFactory.ParseName(rewritten);
    }
}

internal static class SelfCheckCompiler
{
    public static int Check(IReadOnlyDictionary<string, string> sources, HashSet<string> symbols, HashSet<string> implicitUsings)
    {
        CSharpParseOptions parseOptions = new(languageVersion: LanguageVersion.Preview, preprocessorSymbols: symbols);
        List<SyntaxTree> trees = [];
        if (implicitUsings.Count > 0)
        {
            StringBuilder implicitUsingsBuilder = new();
            foreach (string ns in implicitUsings.OrderBy(x => x, StringComparer.Ordinal))
                implicitUsingsBuilder.AppendLine($"global using {ns};");
            trees.Add(CSharpSyntaxTree.ParseText(implicitUsingsBuilder.ToString(), parseOptions, "__implicit_usings.g.cs"));
        }

        foreach ((string path, string content) in sources)
            trees.Add(CSharpSyntaxTree.ParseText(content, parseOptions, path));

        List<MetadataReference> references = [];
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (!String.IsNullOrWhiteSpace(tpa))
        {
            foreach (string assemblyPath in tpa.Split(Path.PathSeparator))
                references.Add(MetadataReference.CreateFromFile(assemblyPath));
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "FastCloner.Internalized.Check",
            trees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        ImmutableArray<Diagnostic> diagnostics = compilation.GetDiagnostics();
        int errors = diagnostics.Count(d => d.Severity == DiagnosticSeverity.Error);
        foreach (Diagnostic diagnostic in diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error))
            Console.Error.WriteLine(diagnostic.ToString());

        return errors;
    }
}
